# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 1
#
# Types: Registry: 1
# Severity: Critical: 1

$results = @{}

# --- Registry Checks (1) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Kernel DMA Protection' -Name 'DeviceEnumerationPolicy' -ErrorAction Stop
    $results['REG-Windows-Kernel DMA Protection-DeviceEnumerationPolicy'] = $v.'DeviceEnumerationPolicy'
} catch { $results['REG-Windows-Kernel DMA Protection-DeviceEnumerationPolicy'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

