# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 24
#
# Types: Registry: 24
# Severity: High: 24

$results = @{}

# --- Registry Checks (24) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall' -Name 'PolicyVersion' -ErrorAction Stop
    $results['REG-Microsoft-WindowsFirewall-PolicyVersion'] = $v.'PolicyVersion'
} catch { $results['REG-Microsoft-WindowsFirewall-PolicyVersion'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DefaultOutboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-DefaultOutboundAction'] = $v.'DefaultOutboundAction'
} catch { $results['REG-WindowsFirewall-DomainProfile-DefaultOutboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DisableNotifications' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-DisableNotifications'] = $v.'DisableNotifications'
} catch { $results['REG-WindowsFirewall-DomainProfile-DisableNotifications'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'EnableFirewall' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-EnableFirewall'] = $v.'EnableFirewall'
} catch { $results['REG-WindowsFirewall-DomainProfile-EnableFirewall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DefaultInboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-DefaultInboundAction'] = $v.'DefaultInboundAction'
} catch { $results['REG-WindowsFirewall-DomainProfile-DefaultInboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogDroppedPackets' -ErrorAction Stop
    $results['REG-DomainProfile-Logging-LogDroppedPackets'] = $v.'LogDroppedPackets'
} catch { $results['REG-DomainProfile-Logging-LogDroppedPackets'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogFileSize' -ErrorAction Stop
    $results['REG-DomainProfile-Logging-LogFileSize'] = $v.'LogFileSize'
} catch { $results['REG-DomainProfile-Logging-LogFileSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogSuccessfulConnections' -ErrorAction Stop
    $results['REG-DomainProfile-Logging-LogSuccessfulConnections'] = $v.'LogSuccessfulConnections'
} catch { $results['REG-DomainProfile-Logging-LogSuccessfulConnections'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'EnableFirewall' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-EnableFirewall'] = $v.'EnableFirewall'
} catch { $results['REG-WindowsFirewall-PrivateProfile-EnableFirewall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DisableNotifications' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-DisableNotifications'] = $v.'DisableNotifications'
} catch { $results['REG-WindowsFirewall-PrivateProfile-DisableNotifications'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DefaultInboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-DefaultInboundAction'] = $v.'DefaultInboundAction'
} catch { $results['REG-WindowsFirewall-PrivateProfile-DefaultInboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DefaultOutboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-DefaultOutboundAction'] = $v.'DefaultOutboundAction'
} catch { $results['REG-WindowsFirewall-PrivateProfile-DefaultOutboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogSuccessfulConnections' -ErrorAction Stop
    $results['REG-PrivateProfile-Logging-LogSuccessfulConnections'] = $v.'LogSuccessfulConnections'
} catch { $results['REG-PrivateProfile-Logging-LogSuccessfulConnections'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogDroppedPackets' -ErrorAction Stop
    $results['REG-PrivateProfile-Logging-LogDroppedPackets'] = $v.'LogDroppedPackets'
} catch { $results['REG-PrivateProfile-Logging-LogDroppedPackets'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogFileSize' -ErrorAction Stop
    $results['REG-PrivateProfile-Logging-LogFileSize'] = $v.'LogFileSize'
} catch { $results['REG-PrivateProfile-Logging-LogFileSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DefaultOutboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-DefaultOutboundAction'] = $v.'DefaultOutboundAction'
} catch { $results['REG-WindowsFirewall-PublicProfile-DefaultOutboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'EnableFirewall' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-EnableFirewall'] = $v.'EnableFirewall'
} catch { $results['REG-WindowsFirewall-PublicProfile-EnableFirewall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DisableNotifications' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-DisableNotifications'] = $v.'DisableNotifications'
} catch { $results['REG-WindowsFirewall-PublicProfile-DisableNotifications'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'AllowLocalIPsecPolicyMerge' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-AllowLocalIPsecPolicyMerge'] = $v.'AllowLocalIPsecPolicyMerge'
} catch { $results['REG-WindowsFirewall-PublicProfile-AllowLocalIPsecPolicyMerge'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'AllowLocalPolicyMerge' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-AllowLocalPolicyMerge'] = $v.'AllowLocalPolicyMerge'
} catch { $results['REG-WindowsFirewall-PublicProfile-AllowLocalPolicyMerge'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DefaultInboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-DefaultInboundAction'] = $v.'DefaultInboundAction'
} catch { $results['REG-WindowsFirewall-PublicProfile-DefaultInboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogFileSize' -ErrorAction Stop
    $results['REG-PublicProfile-Logging-LogFileSize'] = $v.'LogFileSize'
} catch { $results['REG-PublicProfile-Logging-LogFileSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogDroppedPackets' -ErrorAction Stop
    $results['REG-PublicProfile-Logging-LogDroppedPackets'] = $v.'LogDroppedPackets'
} catch { $results['REG-PublicProfile-Logging-LogDroppedPackets'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogSuccessfulConnections' -ErrorAction Stop
    $results['REG-PublicProfile-Logging-LogSuccessfulConnections'] = $v.'LogSuccessfulConnections'
} catch { $results['REG-PublicProfile-Logging-LogSuccessfulConnections'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

