# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 23
#
# Types: PrivilegeRight: 23
# Severity: Critical: 3, High: 20

$results = @{}

# --- PrivilegeRight Checks (23) ---
$seceditPath = "$env:TEMP\baselineforge_secedit.inf"
try {
    $null = secedit /export /cfg $seceditPath /quiet 2>$null
    $seceditContent = Get-Content -Path $seceditPath -ErrorAction Stop
} catch { $seceditContent = @() }
finally { Remove-Item -Path $seceditPath -Force -ErrorAction SilentlyContinue }
$line = $seceditContent | Where-Object { $_ -match '^SeSecurityPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeSecurityPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeSecurityPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeRestorePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeRestorePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeRestorePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeTakeOwnershipPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeTakeOwnershipPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeTakeOwnershipPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeBackupPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeBackupPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeBackupPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeDenyRemoteInteractiveLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeDenyRemoteInteractiveLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeDenyRemoteInteractiveLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreatePermanentPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreatePermanentPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreatePermanentPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeManageVolumePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeManageVolumePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeManageVolumePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeLoadDriverPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeLoadDriverPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeLoadDriverPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeLockMemoryPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeLockMemoryPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeLockMemoryPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeDenyNetworkLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeDenyNetworkLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeDenyNetworkLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeNetworkLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeNetworkLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeNetworkLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeImpersonatePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeImpersonatePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeImpersonatePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreateTokenPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreateTokenPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreateTokenPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreateGlobalPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreateGlobalPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreateGlobalPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeSystemEnvironmentPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeSystemEnvironmentPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeSystemEnvironmentPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreatePagefilePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreatePagefilePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreatePagefilePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeInteractiveLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeInteractiveLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeInteractiveLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeRemoteShutdownPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeRemoteShutdownPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeRemoteShutdownPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeDebugPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeDebugPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeDebugPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeTrustedCredManAccessPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeTrustedCredManAccessPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeTrustedCredManAccessPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeProfileSingleProcessPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeProfileSingleProcessPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeProfileSingleProcessPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeTcbPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeTcbPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeTcbPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeEnableDelegationPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeEnableDelegationPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeEnableDelegationPrivilege'] = '' }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

