# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 20
#
# Types: Registry: 20
# Severity: Critical: 17, High: 2, Medium: 1

$results = @{}

# --- Registry Checks (20) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters' -Name 'AllowEncryptionOracle' -ErrorAction Stop
    $results['REG-CredSSP-Parameters-AllowEncryptionOracle'] = $v.'AllowEncryptionOracle'
} catch { $results['REG-CredSSP-Parameters-AllowEncryptionOracle'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CredentialsDelegation' -Name 'AllowProtectedCreds' -ErrorAction Stop
    $results['REG-Windows-CredentialsDelegation-AllowProtectedCreds'] = $v.'AllowProtectedCreds'
} catch { $results['REG-Windows-CredentialsDelegation-AllowProtectedCreds'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'RunAsPPL' -ErrorAction Stop
    $results['REG-Control-Lsa-RunAsPPL'] = $v.'RunAsPPL'
} catch { $results['REG-Control-Lsa-RunAsPPL'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'EnableVirtualizationBasedSecurity' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-EnableVirtualizationBasedSecurity'] = $v.'EnableVirtualizationBasedSecurity'
} catch { $results['REG-Windows-DeviceGuard-EnableVirtualizationBasedSecurity'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'RequirePlatformSecurityFeatures' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-RequirePlatformSecurityFeatures'] = $v.'RequirePlatformSecurityFeatures'
} catch { $results['REG-Windows-DeviceGuard-RequirePlatformSecurityFeatures'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'HypervisorEnforcedCodeIntegrity' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-HypervisorEnforcedCodeIntegrity'] = $v.'HypervisorEnforcedCodeIntegrity'
} catch { $results['REG-Windows-DeviceGuard-HypervisorEnforcedCodeIntegrity'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'HVCIMATRequired' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-HVCIMATRequired'] = $v.'HVCIMATRequired'
} catch { $results['REG-Windows-DeviceGuard-HVCIMATRequired'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'LsaCfgFlags' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-LsaCfgFlags'] = $v.'LsaCfgFlags'
} catch { $results['REG-Windows-DeviceGuard-LsaCfgFlags'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'MachineIdentityIsolation' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-MachineIdentityIsolation'] = $v.'MachineIdentityIsolation'
} catch { $results['REG-Windows-DeviceGuard-MachineIdentityIsolation'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'ConfigureSystemGuardLaunch' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-ConfigureSystemGuardLaunch'] = $v.'ConfigureSystemGuardLaunch'
} catch { $results['REG-Windows-DeviceGuard-ConfigureSystemGuardLaunch'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'ConfigureKernelShadowStacksLaunch' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-ConfigureKernelShadowStacksLaunch'] = $v.'ConfigureKernelShadowStacksLaunch'
} catch { $results['REG-Windows-DeviceGuard-ConfigureKernelShadowStacksLaunch'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse' -ErrorAction Stop
    $results['REG-Control-Lsa-LimitBlankPasswordUse'] = $v.'LimitBlankPasswordUse'
} catch { $results['REG-Control-Lsa-LimitBlankPasswordUse'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymousSAM' -ErrorAction Stop
    $results['REG-Control-Lsa-RestrictAnonymousSAM'] = $v.'RestrictAnonymousSAM'
} catch { $results['REG-Control-Lsa-RestrictAnonymousSAM'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymous' -ErrorAction Stop
    $results['REG-Control-Lsa-RestrictAnonymous'] = $v.'RestrictAnonymous'
} catch { $results['REG-Control-Lsa-RestrictAnonymous'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'SCENoApplyLegacyAuditPolicy' -ErrorAction Stop
    $results['REG-Control-Lsa-SCENoApplyLegacyAuditPolicy'] = $v.'SCENoApplyLegacyAuditPolicy'
} catch { $results['REG-Control-Lsa-SCENoApplyLegacyAuditPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinClientSec' -ErrorAction Stop
    $results['REG-Lsa-MSV1_0-NTLMMinClientSec'] = $v.'NTLMMinClientSec'
} catch { $results['REG-Lsa-MSV1_0-NTLMMinClientSec'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LmCompatibilityLevel' -ErrorAction Stop
    $results['REG-Control-Lsa-LmCompatibilityLevel'] = $v.'LmCompatibilityLevel'
} catch { $results['REG-Control-Lsa-LmCompatibilityLevel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'allownullsessionfallback' -ErrorAction Stop
    $results['REG-Lsa-MSV1_0-allownullsessionfallback'] = $v.'allownullsessionfallback'
} catch { $results['REG-Lsa-MSV1_0-allownullsessionfallback'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinServerSec' -ErrorAction Stop
    $results['REG-Lsa-MSV1_0-NTLMMinServerSec'] = $v.'NTLMMinServerSec'
} catch { $results['REG-Lsa-MSV1_0-NTLMMinServerSec'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictRemoteSAM' -ErrorAction Stop
    $results['REG-Control-Lsa-RestrictRemoteSAM'] = $v.'RestrictRemoteSAM'
} catch { $results['REG-Control-Lsa-RestrictRemoteSAM'] = 'NOT_FOUND' }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

