# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 16
#
# Types: Registry: 16
# Severity: Critical: 3, High: 3, Medium: 10

$results = @{}

# --- Registry Checks (16) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'MSAOptional' -ErrorAction Stop
    $results['REG-Policies-System-MSAOptional'] = $v.'MSAOptional'
} catch { $results['REG-Policies-System-MSAOptional'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableAutomaticRestartSignOn' -ErrorAction Stop
    $results['REG-Policies-System-DisableAutomaticRestartSignOn'] = $v.'DisableAutomaticRestartSignOn'
} catch { $results['REG-Policies-System-DisableAutomaticRestartSignOn'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LocalAccountTokenFilterPolicy' -ErrorAction Stop
    $results['REG-Policies-System-LocalAccountTokenFilterPolicy'] = $v.'LocalAccountTokenFilterPolicy'
} catch { $results['REG-Policies-System-LocalAccountTokenFilterPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableMPR' -ErrorAction Stop
    $results['REG-Policies-System-EnableMPR'] = $v.'EnableMPR'
} catch { $results['REG-Policies-System-EnableMPR'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit' -Name 'ProcessCreationIncludeCmdLine_Enabled' -ErrorAction Stop
    $results['REG-System-Audit-ProcessCreationIncludeCmdLine_Enabled'] = $v.'ProcessCreationIncludeCmdLine_Enabled'
} catch { $results['REG-System-Audit-ProcessCreationIncludeCmdLine_Enabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorEnhancedAdmin' -ErrorAction Stop
    $results['REG-Policies-System-ConsentPromptBehaviorEnhancedAdmin'] = $v.'ConsentPromptBehaviorEnhancedAdmin'
} catch { $results['REG-Policies-System-ConsentPromptBehaviorEnhancedAdmin'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'TypeOfAdminApprovalMode' -ErrorAction Stop
    $results['REG-Policies-System-TypeOfAdminApprovalMode'] = $v.'TypeOfAdminApprovalMode'
} catch { $results['REG-Policies-System-TypeOfAdminApprovalMode'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScRemoveOption' -ErrorAction Stop
    $results['REG-CurrentVersion-Winlogon-ScRemoveOption'] = $v.'ScRemoveOption'
} catch { $results['REG-CurrentVersion-Winlogon-ScRemoveOption'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'InactivityTimeoutSecs' -ErrorAction Stop
    $results['REG-Policies-System-InactivityTimeoutSecs'] = $v.'InactivityTimeoutSecs'
} catch { $results['REG-Policies-System-InactivityTimeoutSecs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorAdmin' -ErrorAction Stop
    $results['REG-Policies-System-ConsentPromptBehaviorAdmin'] = $v.'ConsentPromptBehaviorAdmin'
} catch { $results['REG-Policies-System-ConsentPromptBehaviorAdmin'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableSecureUIAPaths' -ErrorAction Stop
    $results['REG-Policies-System-EnableSecureUIAPaths'] = $v.'EnableSecureUIAPaths'
} catch { $results['REG-Policies-System-EnableSecureUIAPaths'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableLUA' -ErrorAction Stop
    $results['REG-Policies-System-EnableLUA'] = $v.'EnableLUA'
} catch { $results['REG-Policies-System-EnableLUA'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorUser' -ErrorAction Stop
    $results['REG-Policies-System-ConsentPromptBehaviorUser'] = $v.'ConsentPromptBehaviorUser'
} catch { $results['REG-Policies-System-ConsentPromptBehaviorUser'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableInstallerDetection' -ErrorAction Stop
    $results['REG-Policies-System-EnableInstallerDetection'] = $v.'EnableInstallerDetection'
} catch { $results['REG-Policies-System-EnableInstallerDetection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'FilterAdministratorToken' -ErrorAction Stop
    $results['REG-Policies-System-FilterAdministratorToken'] = $v.'FilterAdministratorToken'
} catch { $results['REG-Policies-System-FilterAdministratorToken'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableVirtualization' -ErrorAction Stop
    $results['REG-Policies-System-EnableVirtualization'] = $v.'EnableVirtualization'
} catch { $results['REG-Policies-System-EnableVirtualization'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

