# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 4
#
# Types: Registry: 4
# Severity: Low: 4

$results = @{}

# --- Registry Checks (4) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51' -Name 'DCSettingIndex' -ErrorAction Stop
    $results['REG-PowerSettings-0e796bdb-100d-47d6-a2d5-f7d2daa51f51-DCSettingIndex'] = $v.'DCSettingIndex'
} catch { $results['REG-PowerSettings-0e796bdb-100d-47d6-a2d5-f7d2daa51f51-DCSettingIndex'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51' -Name 'ACSettingIndex' -ErrorAction Stop
    $results['REG-PowerSettings-0e796bdb-100d-47d6-a2d5-f7d2daa51f51-ACSettingIndex'] = $v.'ACSettingIndex'
} catch { $results['REG-PowerSettings-0e796bdb-100d-47d6-a2d5-f7d2daa51f51-ACSettingIndex'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\abfc2519-3608-4c2a-94ea-171b0ed546ab' -Name 'DCSettingIndex' -ErrorAction Stop
    $results['REG-PowerSettings-abfc2519-3608-4c2a-94ea-171b0ed546ab-DCSettingIndex'] = $v.'DCSettingIndex'
} catch { $results['REG-PowerSettings-abfc2519-3608-4c2a-94ea-171b0ed546ab-DCSettingIndex'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\abfc2519-3608-4c2a-94ea-171b0ed546ab' -Name 'ACSettingIndex' -ErrorAction Stop
    $results['REG-PowerSettings-abfc2519-3608-4c2a-94ea-171b0ed546ab-ACSettingIndex'] = $v.'ACSettingIndex'
} catch { $results['REG-PowerSettings-abfc2519-3608-4c2a-94ea-171b0ed546ab-ACSettingIndex'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

