# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 13
#
# Types: Registry: 13
# Severity: Critical: 1, High: 1, Low: 1, Medium: 10

$results = @{}

# --- Registry Checks (13) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoDriveTypeAutoRun' -ErrorAction Stop
    $results['REG-Policies-Explorer-NoDriveTypeAutoRun'] = $v.'NoDriveTypeAutoRun'
} catch { $results['REG-Policies-Explorer-NoDriveTypeAutoRun'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoWebServices' -ErrorAction Stop
    $results['REG-Policies-Explorer-NoWebServices'] = $v.'NoWebServices'
} catch { $results['REG-Policies-Explorer-NoWebServices'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoAutorun' -ErrorAction Stop
    $results['REG-Policies-Explorer-NoAutorun'] = $v.'NoAutorun'
} catch { $results['REG-Policies-Explorer-NoAutorun'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\AppPrivacy' -Name 'LetAppsActivateWithVoiceAboveLock' -ErrorAction Stop
    $results['REG-Windows-AppPrivacy-LetAppsActivateWithVoiceAboveLock'] = $v.'LetAppsActivateWithVoiceAboveLock'
} catch { $results['REG-Windows-AppPrivacy-LetAppsActivateWithVoiceAboveLock'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoAutoplayfornonVolume' -ErrorAction Stop
    $results['REG-Windows-Explorer-NoAutoplayfornonVolume'] = $v.'NoAutoplayfornonVolume'
} catch { $results['REG-Windows-Explorer-NoAutoplayfornonVolume'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'DisableMotWOnInsecurePathCopy' -ErrorAction Stop
    $results['REG-Windows-Explorer-DisableMotWOnInsecurePathCopy'] = $v.'DisableMotWOnInsecurePathCopy'
} catch { $results['REG-Windows-Explorer-DisableMotWOnInsecurePathCopy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\GameDVR' -Name 'AllowGameDVR' -ErrorAction Stop
    $results['REG-Windows-GameDVR-AllowGameDVR'] = $v.'AllowGameDVR'
} catch { $results['REG-Windows-GameDVR-AllowGameDVR'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated' -ErrorAction Stop
    $results['REG-Windows-Installer-AlwaysInstallElevated'] = $v.'AlwaysInstallElevated'
} catch { $results['REG-Windows-Installer-AlwaysInstallElevated'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'EnableUserControl' -ErrorAction Stop
    $results['REG-Windows-Installer-EnableUserControl'] = $v.'EnableUserControl'
} catch { $results['REG-Windows-Installer-EnableUserControl'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging' -Name 'EnableScriptBlockLogging' -ErrorAction Stop
    $results['REG-PowerShell-ScriptBlockLogging-EnableScriptBlockLogging'] = $v.'EnableScriptBlockLogging'
} catch { $results['REG-PowerShell-ScriptBlockLogging-EnableScriptBlockLogging'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging' -Name '**del.EnableScriptBlockInvocationLogging' -ErrorAction Stop
    $results['REG-PowerShell-ScriptBlockLogging-**del.EnableScriptBlockInvocationLogging'] = $v.'**del.EnableScriptBlockInvocationLogging'
} catch { $results['REG-PowerShell-ScriptBlockLogging-**del.EnableScriptBlockInvocationLogging'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsInkWorkspace' -Name 'AllowWindowsInkWorkspace' -ErrorAction Stop
    $results['REG-Microsoft-WindowsInkWorkspace-AllowWindowsInkWorkspace'] = $v.'AllowWindowsInkWorkspace'
} catch { $results['REG-Microsoft-WindowsInkWorkspace-AllowWindowsInkWorkspace'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\AxInstaller' -Name 'OnlyUseAXISForActiveXInstall' -ErrorAction Stop
    $results['REG-Windows-AxInstaller-OnlyUseAXISForActiveXInstall'] = $v.'OnlyUseAXISForActiveXInstall'
} catch { $results['REG-Windows-AxInstaller-OnlyUseAXISForActiveXInstall'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

