# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 3
#
# Types: Registry: 3
# Severity: Medium: 3

$results = @{}

# --- Registry Checks (3) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application' -Name 'MaxSize' -ErrorAction Stop
    $results['REG-EventLog-Application-MaxSize'] = $v.'MaxSize'
} catch { $results['REG-EventLog-Application-MaxSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security' -Name 'MaxSize' -ErrorAction Stop
    $results['REG-EventLog-Security-MaxSize'] = $v.'MaxSize'
} catch { $results['REG-EventLog-Security-MaxSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\System' -Name 'MaxSize' -ErrorAction Stop
    $results['REG-EventLog-System-MaxSize'] = $v.'MaxSize'
} catch { $results['REG-EventLog-System-MaxSize'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

