# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 9
#
# Types: SystemAccess: 9
# Severity: Critical: 1, High: 8

$results = @{}

# --- SystemAccess Checks (9) ---
if (-not $seceditContent) {
    $seceditPath = "$env:TEMP\baselineforge_secedit.inf"
    try {
        $null = secedit /export /cfg $seceditPath /quiet 2>$null
        $seceditContent = Get-Content -Path $seceditPath -ErrorAction Stop
    } catch { $seceditContent = @() }
    finally { Remove-Item -Path $seceditPath -Force -ErrorAction SilentlyContinue }
}
$line = $seceditContent | Where-Object { $_ -match '^LSAAnonymousNameLookup\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-LSAAnonymousNameLookup'] = $Matches[1].Trim() } else { $results['ACC-LSAAnonymousNameLookup'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^MinimumPasswordLength\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-MinimumPasswordLength'] = $Matches[1].Trim() } else { $results['ACC-MinimumPasswordLength'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^PasswordComplexity\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-PasswordComplexity'] = $Matches[1].Trim() } else { $results['ACC-PasswordComplexity'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^PasswordHistorySize\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-PasswordHistorySize'] = $Matches[1].Trim() } else { $results['ACC-PasswordHistorySize'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^LockoutBadCount\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-LockoutBadCount'] = $Matches[1].Trim() } else { $results['ACC-LockoutBadCount'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^ResetLockoutCount\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-ResetLockoutCount'] = $Matches[1].Trim() } else { $results['ACC-ResetLockoutCount'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^LockoutDuration\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-LockoutDuration'] = $Matches[1].Trim() } else { $results['ACC-LockoutDuration'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^AllowAdministratorLockout\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-AllowAdministratorLockout'] = $Matches[1].Trim() } else { $results['ACC-AllowAdministratorLockout'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^ClearTextPassword\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-ClearTextPassword'] = $Matches[1].Trim() } else { $results['ACC-ClearTextPassword'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

