# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 3
#
# Types: Registry: 3
# Severity: High: 3

$results = @{}

# --- Registry Checks (3) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS' -Name 'BackupDirectory' -ErrorAction Stop
    $results['REG-Policies-LAPS-BackupDirectory'] = $v.'BackupDirectory'
} catch { $results['REG-Policies-LAPS-BackupDirectory'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS' -Name 'ADPasswordEncryptionEnabled' -ErrorAction Stop
    $results['REG-Policies-LAPS-ADPasswordEncryptionEnabled'] = $v.'ADPasswordEncryptionEnabled'
} catch { $results['REG-Policies-LAPS-ADPasswordEncryptionEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS' -Name 'ADBackupDSRMPassword' -ErrorAction Stop
    $results['REG-Policies-LAPS-ADBackupDSRMPassword'] = $v.'ADBackupDSRMPassword'
} catch { $results['REG-Policies-LAPS-ADBackupDSRMPassword'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

