# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 4
#
# Types: Registry: 4
# Severity: High: 4

$results = @{}

# --- Registry Checks (4) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'NotifyMalicious' -ErrorAction Stop
    $results['REG-WTDS-Components-NotifyMalicious'] = $v.'NotifyMalicious'
} catch { $results['REG-WTDS-Components-NotifyMalicious'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'NotifyPasswordReuse' -ErrorAction Stop
    $results['REG-WTDS-Components-NotifyPasswordReuse'] = $v.'NotifyPasswordReuse'
} catch { $results['REG-WTDS-Components-NotifyPasswordReuse'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'NotifyUnsafeApp' -ErrorAction Stop
    $results['REG-WTDS-Components-NotifyUnsafeApp'] = $v.'NotifyUnsafeApp'
} catch { $results['REG-WTDS-Components-NotifyUnsafeApp'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'ServiceEnabled' -ErrorAction Stop
    $results['REG-WTDS-Components-ServiceEnabled'] = $v.'ServiceEnabled'
} catch { $results['REG-WTDS-Components-ServiceEnabled'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

