# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 1
#
# Types: Registry: 1
# Severity: Medium: 1

$results = @{}

# --- Registry Checks (1) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Sudo' -Name 'Enabled' -ErrorAction Stop
    $results['REG-Windows-Sudo-Enabled'] = $v.'Enabled'
} catch { $results['REG-Windows-Sudo-Enabled'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

