# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 10
#
# Types: Registry: 10
# Severity: High: 9, Medium: 1

$results = @{}

# --- Registry Checks (10) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Bowser' -Name 'EnableMailslots' -ErrorAction Stop
    $results['REG-Windows-Bowser-EnableMailslots'] = $v.'EnableMailslots'
} catch { $results['REG-Windows-Bowser-EnableMailslots'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AllowInsecureGuestAuth' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AllowInsecureGuestAuth'] = $v.'AllowInsecureGuestAuth'
} catch { $results['REG-Windows-LanmanWorkstation-AllowInsecureGuestAuth'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AuditInsecureGuestLogon' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AuditInsecureGuestLogon'] = $v.'AuditInsecureGuestLogon'
} catch { $results['REG-Windows-LanmanWorkstation-AuditInsecureGuestLogon'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AuditServerDoesNotSupportEncryption' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportEncryption'] = $v.'AuditServerDoesNotSupportEncryption'
} catch { $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportEncryption'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AuditServerDoesNotSupportSigning' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportSigning'] = $v.'AuditServerDoesNotSupportSigning'
} catch { $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportSigning'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'MaxSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-MaxSmb2Dialect'] = $v.'MaxSmb2Dialect'
} catch { $results['REG-Windows-LanmanWorkstation-MaxSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'MinSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-MinSmb2Dialect'] = $v.'MinSmb2Dialect'
} catch { $results['REG-Windows-LanmanWorkstation-MinSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'RequireEncryption' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-RequireEncryption'] = $v.'RequireEncryption'
} catch { $results['REG-Windows-LanmanWorkstation-RequireEncryption'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnablePlainTextPassword' -ErrorAction Stop
    $results['REG-LanmanWorkstation-Parameters-EnablePlainTextPassword'] = $v.'EnablePlainTextPassword'
} catch { $results['REG-LanmanWorkstation-Parameters-EnablePlainTextPassword'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'RequireSecuritySignature' -ErrorAction Stop
    $results['REG-LanmanWorkstation-Parameters-RequireSecuritySignature'] = $v.'RequireSecuritySignature'
} catch { $results['REG-LanmanWorkstation-Parameters-RequireSecuritySignature'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

