# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 5
#
# Types: Registry: 5
# Severity: Critical: 1, Medium: 4

$results = @{}

# --- Registry Checks (5) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Kernel DMA Protection' -Name 'DeviceEnumerationPolicy' -ErrorAction Stop
    $results['REG-Windows-Kernel DMA Protection-DeviceEnumerationPolicy'] = $v.'DeviceEnumerationPolicy'
} catch { $results['REG-Windows-Kernel DMA Protection-DeviceEnumerationPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions' -Name 'DenyDeviceClasses' -ErrorAction Stop
    $results['REG-DeviceInstall-Restrictions-DenyDeviceClasses'] = $v.'DenyDeviceClasses'
} catch { $results['REG-DeviceInstall-Restrictions-DenyDeviceClasses'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions' -Name 'DenyDeviceClassesRetroactive' -ErrorAction Stop
    $results['REG-DeviceInstall-Restrictions-DenyDeviceClassesRetroactive'] = $v.'DenyDeviceClassesRetroactive'
} catch { $results['REG-DeviceInstall-Restrictions-DenyDeviceClassesRetroactive'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceClasses' -Name '**delvals.' -ErrorAction Stop
    $results['REG-Restrictions-DenyDeviceClasses-**delvals.'] = $v.'**delvals.'
} catch { $results['REG-Restrictions-DenyDeviceClasses-**delvals.'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Restrictions\DenyDeviceClasses' -Name '1' -ErrorAction Stop
    $results['REG-Restrictions-DenyDeviceClasses-1'] = $v.'1'
} catch { $results['REG-Restrictions-DenyDeviceClasses-1'] = 'NOT_FOUND' }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

