# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 1
#
# Types: Registry: 1
# Severity: Medium: 1

$results = @{}

# --- Registry Checks (1) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Biometrics\FacialFeatures' -Name 'EnhancedAntiSpoofing' -ErrorAction Stop
    $results['REG-Biometrics-FacialFeatures-EnhancedAntiSpoofing'] = $v.'EnhancedAntiSpoofing'
} catch { $results['REG-Biometrics-FacialFeatures-EnhancedAntiSpoofing'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

