# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 63
#
# Types: PrivilegeRight: 23, Registry: 31, SystemAccess: 9
# Severity: Critical: 7, High: 34, Medium: 22

$results = @{}

# --- PrivilegeRight Checks (23) ---
$seceditPath = "$env:TEMP\baselineforge_secedit.inf"
try {
    $null = secedit /export /cfg $seceditPath /quiet 2>$null
    $seceditContent = Get-Content -Path $seceditPath -ErrorAction Stop
} catch { $seceditContent = @() }
finally { Remove-Item -Path $seceditPath -Force -ErrorAction SilentlyContinue }
$line = $seceditContent | Where-Object { $_ -match '^SeSecurityPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeSecurityPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeSecurityPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeRestorePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeRestorePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeRestorePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeTakeOwnershipPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeTakeOwnershipPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeTakeOwnershipPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeBackupPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeBackupPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeBackupPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeDenyRemoteInteractiveLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeDenyRemoteInteractiveLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeDenyRemoteInteractiveLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreatePermanentPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreatePermanentPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreatePermanentPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeManageVolumePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeManageVolumePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeManageVolumePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeLoadDriverPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeLoadDriverPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeLoadDriverPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeLockMemoryPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeLockMemoryPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeLockMemoryPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeDenyNetworkLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeDenyNetworkLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeDenyNetworkLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeNetworkLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeNetworkLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeNetworkLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeImpersonatePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeImpersonatePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeImpersonatePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreateTokenPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreateTokenPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreateTokenPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreateGlobalPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreateGlobalPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreateGlobalPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeSystemEnvironmentPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeSystemEnvironmentPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeSystemEnvironmentPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeCreatePagefilePrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeCreatePagefilePrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeCreatePagefilePrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeInteractiveLogonRight\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeInteractiveLogonRight'] = $Matches[1].Trim() } else { $results['PRV-SeInteractiveLogonRight'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeRemoteShutdownPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeRemoteShutdownPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeRemoteShutdownPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeDebugPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeDebugPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeDebugPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeTrustedCredManAccessPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeTrustedCredManAccessPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeTrustedCredManAccessPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeProfileSingleProcessPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeProfileSingleProcessPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeProfileSingleProcessPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeTcbPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeTcbPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeTcbPrivilege'] = '' }
$line = $seceditContent | Where-Object { $_ -match '^SeEnableDelegationPrivilege\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['PRV-SeEnableDelegationPrivilege'] = $Matches[1].Trim() } else { $results['PRV-SeEnableDelegationPrivilege'] = '' }

# --- Registry Checks (31) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\CredUI' -Name 'EnumerateAdministrators' -ErrorAction Stop
    $results['REG-Policies-CredUI-EnumerateAdministrators'] = $v.'EnumerateAdministrators'
} catch { $results['REG-Policies-CredUI-EnumerateAdministrators'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS' -Name 'BackupDirectory' -ErrorAction Stop
    $results['REG-Policies-LAPS-BackupDirectory'] = $v.'BackupDirectory'
} catch { $results['REG-Policies-LAPS-BackupDirectory'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS' -Name 'ADPasswordEncryptionEnabled' -ErrorAction Stop
    $results['REG-Policies-LAPS-ADPasswordEncryptionEnabled'] = $v.'ADPasswordEncryptionEnabled'
} catch { $results['REG-Policies-LAPS-ADPasswordEncryptionEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS' -Name 'ADBackupDSRMPassword' -ErrorAction Stop
    $results['REG-Policies-LAPS-ADBackupDSRMPassword'] = $v.'ADBackupDSRMPassword'
} catch { $results['REG-Policies-LAPS-ADBackupDSRMPassword'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'MSAOptional' -ErrorAction Stop
    $results['REG-Policies-System-MSAOptional'] = $v.'MSAOptional'
} catch { $results['REG-Policies-System-MSAOptional'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableAutomaticRestartSignOn' -ErrorAction Stop
    $results['REG-Policies-System-DisableAutomaticRestartSignOn'] = $v.'DisableAutomaticRestartSignOn'
} catch { $results['REG-Policies-System-DisableAutomaticRestartSignOn'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LocalAccountTokenFilterPolicy' -ErrorAction Stop
    $results['REG-Policies-System-LocalAccountTokenFilterPolicy'] = $v.'LocalAccountTokenFilterPolicy'
} catch { $results['REG-Policies-System-LocalAccountTokenFilterPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableMPR' -ErrorAction Stop
    $results['REG-Policies-System-EnableMPR'] = $v.'EnableMPR'
} catch { $results['REG-Policies-System-EnableMPR'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit' -Name 'ProcessCreationIncludeCmdLine_Enabled' -ErrorAction Stop
    $results['REG-System-Audit-ProcessCreationIncludeCmdLine_Enabled'] = $v.'ProcessCreationIncludeCmdLine_Enabled'
} catch { $results['REG-System-Audit-ProcessCreationIncludeCmdLine_Enabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITHashAlgorithmConfigurationEnabled' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITHashAlgorithmConfigurationEnabled'] = $v.'PKINITHashAlgorithmConfigurationEnabled'
} catch { $results['REG-KDC-Parameters-PKINITHashAlgorithmConfigurationEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA1' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA1'] = $v.'PKINITSHA1'
} catch { $results['REG-KDC-Parameters-PKINITSHA1'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA256' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA256'] = $v.'PKINITSHA256'
} catch { $results['REG-KDC-Parameters-PKINITSHA256'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA384' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA384'] = $v.'PKINITSHA384'
} catch { $results['REG-KDC-Parameters-PKINITSHA384'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA512' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA512'] = $v.'PKINITSHA512'
} catch { $results['REG-KDC-Parameters-PKINITSHA512'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitHashAlgorithmConfigurationEnabled' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitHashAlgorithmConfigurationEnabled'] = $v.'PKInitHashAlgorithmConfigurationEnabled'
} catch { $results['REG-Kerberos-Parameters-PKInitHashAlgorithmConfigurationEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA1' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA1'] = $v.'PKInitSHA1'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA1'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA256' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA256'] = $v.'PKInitSHA256'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA256'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA384' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA384'] = $v.'PKInitSHA384'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA384'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA512' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA512'] = $v.'PKInitSHA512'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA512'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Sudo' -Name 'Enabled' -ErrorAction Stop
    $results['REG-Windows-Sudo-Enabled'] = $v.'Enabled'
} catch { $results['REG-Windows-Sudo-Enabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorEnhancedAdmin' -ErrorAction Stop
    $results['REG-Policies-System-ConsentPromptBehaviorEnhancedAdmin'] = $v.'ConsentPromptBehaviorEnhancedAdmin'
} catch { $results['REG-Policies-System-ConsentPromptBehaviorEnhancedAdmin'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'TypeOfAdminApprovalMode' -ErrorAction Stop
    $results['REG-Policies-System-TypeOfAdminApprovalMode'] = $v.'TypeOfAdminApprovalMode'
} catch { $results['REG-Policies-System-TypeOfAdminApprovalMode'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScRemoveOption' -ErrorAction Stop
    $results['REG-CurrentVersion-Winlogon-ScRemoveOption'] = $v.'ScRemoveOption'
} catch { $results['REG-CurrentVersion-Winlogon-ScRemoveOption'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'InactivityTimeoutSecs' -ErrorAction Stop
    $results['REG-Policies-System-InactivityTimeoutSecs'] = $v.'InactivityTimeoutSecs'
} catch { $results['REG-Policies-System-InactivityTimeoutSecs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorAdmin' -ErrorAction Stop
    $results['REG-Policies-System-ConsentPromptBehaviorAdmin'] = $v.'ConsentPromptBehaviorAdmin'
} catch { $results['REG-Policies-System-ConsentPromptBehaviorAdmin'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableSecureUIAPaths' -ErrorAction Stop
    $results['REG-Policies-System-EnableSecureUIAPaths'] = $v.'EnableSecureUIAPaths'
} catch { $results['REG-Policies-System-EnableSecureUIAPaths'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableLUA' -ErrorAction Stop
    $results['REG-Policies-System-EnableLUA'] = $v.'EnableLUA'
} catch { $results['REG-Policies-System-EnableLUA'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorUser' -ErrorAction Stop
    $results['REG-Policies-System-ConsentPromptBehaviorUser'] = $v.'ConsentPromptBehaviorUser'
} catch { $results['REG-Policies-System-ConsentPromptBehaviorUser'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableInstallerDetection' -ErrorAction Stop
    $results['REG-Policies-System-EnableInstallerDetection'] = $v.'EnableInstallerDetection'
} catch { $results['REG-Policies-System-EnableInstallerDetection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'FilterAdministratorToken' -ErrorAction Stop
    $results['REG-Policies-System-FilterAdministratorToken'] = $v.'FilterAdministratorToken'
} catch { $results['REG-Policies-System-FilterAdministratorToken'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableVirtualization' -ErrorAction Stop
    $results['REG-Policies-System-EnableVirtualization'] = $v.'EnableVirtualization'
} catch { $results['REG-Policies-System-EnableVirtualization'] = -1 }

# --- SystemAccess Checks (9) ---
if (-not $seceditContent) {
    $seceditPath = "$env:TEMP\baselineforge_secedit.inf"
    try {
        $null = secedit /export /cfg $seceditPath /quiet 2>$null
        $seceditContent = Get-Content -Path $seceditPath -ErrorAction Stop
    } catch { $seceditContent = @() }
    finally { Remove-Item -Path $seceditPath -Force -ErrorAction SilentlyContinue }
}
$line = $seceditContent | Where-Object { $_ -match '^LSAAnonymousNameLookup\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-LSAAnonymousNameLookup'] = $Matches[1].Trim() } else { $results['ACC-LSAAnonymousNameLookup'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^MinimumPasswordLength\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-MinimumPasswordLength'] = $Matches[1].Trim() } else { $results['ACC-MinimumPasswordLength'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^PasswordComplexity\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-PasswordComplexity'] = $Matches[1].Trim() } else { $results['ACC-PasswordComplexity'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^PasswordHistorySize\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-PasswordHistorySize'] = $Matches[1].Trim() } else { $results['ACC-PasswordHistorySize'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^LockoutBadCount\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-LockoutBadCount'] = $Matches[1].Trim() } else { $results['ACC-LockoutBadCount'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^ResetLockoutCount\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-ResetLockoutCount'] = $Matches[1].Trim() } else { $results['ACC-ResetLockoutCount'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^LockoutDuration\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-LockoutDuration'] = $Matches[1].Trim() } else { $results['ACC-LockoutDuration'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^AllowAdministratorLockout\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-AllowAdministratorLockout'] = $Matches[1].Trim() } else { $results['ACC-AllowAdministratorLockout'] = -1 }
$line = $seceditContent | Where-Object { $_ -match '^ClearTextPassword\s*=' } | Select-Object -First 1
if ($line -and $line -match '=\s*(.*)') { $results['ACC-ClearTextPassword'] = $Matches[1].Trim() } else { $results['ACC-ClearTextPassword'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

