# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 71
#
# Types: Registry: 71
# Severity: High: 55, Medium: 16

$results = @{}

# --- Registry Checks (71) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\WcmSvc\wifinetworkmanager\config' -Name 'AutoConnectAllowedOEM' -ErrorAction Stop
    $results['REG-wifinetworkmanager-config-AutoConnectAllowedOEM'] = $v.'AutoConnectAllowedOEM'
} catch { $results['REG-wifinetworkmanager-config-AutoConnectAllowedOEM'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Bowser' -Name 'EnableMailslots' -ErrorAction Stop
    $results['REG-Windows-Bowser-EnableMailslots'] = $v.'EnableMailslots'
} catch { $results['REG-Windows-Bowser-EnableMailslots'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'AuditClientDoesNotSupportEncryption' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportEncryption'] = $v.'AuditClientDoesNotSupportEncryption'
} catch { $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportEncryption'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'AuditClientDoesNotSupportSigning' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportSigning'] = $v.'AuditClientDoesNotSupportSigning'
} catch { $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportSigning'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'AuditInsecureGuestLogon' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-AuditInsecureGuestLogon'] = $v.'AuditInsecureGuestLogon'
} catch { $results['REG-Windows-LanmanServer-AuditInsecureGuestLogon'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'EnableAuthRateLimiter' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-EnableAuthRateLimiter'] = $v.'EnableAuthRateLimiter'
} catch { $results['REG-Windows-LanmanServer-EnableAuthRateLimiter'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'MaxSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-MaxSmb2Dialect'] = $v.'MaxSmb2Dialect'
} catch { $results['REG-Windows-LanmanServer-MaxSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'MinSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-MinSmb2Dialect'] = $v.'MinSmb2Dialect'
} catch { $results['REG-Windows-LanmanServer-MinSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'InvalidAuthenticationDelayTimeInMs' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-InvalidAuthenticationDelayTimeInMs'] = $v.'InvalidAuthenticationDelayTimeInMs'
} catch { $results['REG-Windows-LanmanServer-InvalidAuthenticationDelayTimeInMs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AllowInsecureGuestAuth' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AllowInsecureGuestAuth'] = $v.'AllowInsecureGuestAuth'
} catch { $results['REG-Windows-LanmanWorkstation-AllowInsecureGuestAuth'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AuditInsecureGuestLogon' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AuditInsecureGuestLogon'] = $v.'AuditInsecureGuestLogon'
} catch { $results['REG-Windows-LanmanWorkstation-AuditInsecureGuestLogon'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AuditServerDoesNotSupportEncryption' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportEncryption'] = $v.'AuditServerDoesNotSupportEncryption'
} catch { $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportEncryption'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AuditServerDoesNotSupportSigning' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportSigning'] = $v.'AuditServerDoesNotSupportSigning'
} catch { $results['REG-Windows-LanmanWorkstation-AuditServerDoesNotSupportSigning'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'MaxSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-MaxSmb2Dialect'] = $v.'MaxSmb2Dialect'
} catch { $results['REG-Windows-LanmanWorkstation-MaxSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'MinSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-MinSmb2Dialect'] = $v.'MinSmb2Dialect'
} catch { $results['REG-Windows-LanmanWorkstation-MinSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'RequireEncryption' -ErrorAction Stop
    $results['REG-Windows-LanmanWorkstation-RequireEncryption'] = $v.'RequireEncryption'
} catch { $results['REG-Windows-LanmanWorkstation-RequireEncryption'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_ShowSharedAccessUI' -ErrorAction Stop
    $results['REG-Windows-Network Connections-NC_ShowSharedAccessUI'] = $v.'NC_ShowSharedAccessUI'
} catch { $results['REG-Windows-Network Connections-NC_ShowSharedAccessUI'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider' -Name 'EnableMailslots' -ErrorAction Stop
    $results['REG-Windows-NetworkProvider-EnableMailslots'] = $v.'EnableMailslots'
} catch { $results['REG-Windows-NetworkProvider-EnableMailslots'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\SYSVOL' -ErrorAction Stop
    $results['REG--*-SYSVOL'] = $v.'\\*\SYSVOL'
} catch { $results['REG--*-SYSVOL'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\NETLOGON' -ErrorAction Stop
    $results['REG--*-NETLOGON'] = $v.'\\*\NETLOGON'
} catch { $results['REG--*-NETLOGON'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy' -Name 'fBlockNonDomain' -ErrorAction Stop
    $results['REG-WcmSvc-GroupPolicy-fBlockNonDomain'] = $v.'fBlockNonDomain'
} catch { $results['REG-WcmSvc-GroupPolicy-fBlockNonDomain'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowDigest' -ErrorAction Stop
    $results['REG-WinRM-Client-AllowDigest'] = $v.'AllowDigest'
} catch { $results['REG-WinRM-Client-AllowDigest'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowUnencryptedTraffic' -ErrorAction Stop
    $results['REG-WinRM-Client-AllowUnencryptedTraffic'] = $v.'AllowUnencryptedTraffic'
} catch { $results['REG-WinRM-Client-AllowUnencryptedTraffic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowBasic' -ErrorAction Stop
    $results['REG-WinRM-Client-AllowBasic'] = $v.'AllowBasic'
} catch { $results['REG-WinRM-Client-AllowBasic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowUnencryptedTraffic' -ErrorAction Stop
    $results['REG-WinRM-Service-AllowUnencryptedTraffic'] = $v.'AllowUnencryptedTraffic'
} catch { $results['REG-WinRM-Service-AllowUnencryptedTraffic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'DisableRunAs' -ErrorAction Stop
    $results['REG-WinRM-Service-DisableRunAs'] = $v.'DisableRunAs'
} catch { $results['REG-WinRM-Service-DisableRunAs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowBasic' -ErrorAction Stop
    $results['REG-WinRM-Service-AllowBasic'] = $v.'AllowBasic'
} catch { $results['REG-WinRM-Service-AllowBasic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableMulticast' -ErrorAction Stop
    $results['REG-Windows NT-DNSClient-EnableMulticast'] = $v.'EnableMulticast'
} catch { $results['REG-Windows NT-DNSClient-EnableMulticast'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableNetbios' -ErrorAction Stop
    $results['REG-Windows NT-DNSClient-EnableNetbios'] = $v.'EnableNetbios'
} catch { $results['REG-Windows NT-DNSClient-EnableNetbios'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Rpc' -Name 'RestrictRemoteClients' -ErrorAction Stop
    $results['REG-Windows NT-Rpc-RestrictRemoteClients'] = $v.'RestrictRemoteClients'
} catch { $results['REG-Windows NT-Rpc-RestrictRemoteClients'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall' -Name 'PolicyVersion' -ErrorAction Stop
    $results['REG-Microsoft-WindowsFirewall-PolicyVersion'] = $v.'PolicyVersion'
} catch { $results['REG-Microsoft-WindowsFirewall-PolicyVersion'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DefaultOutboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-DefaultOutboundAction'] = $v.'DefaultOutboundAction'
} catch { $results['REG-WindowsFirewall-DomainProfile-DefaultOutboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DisableNotifications' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-DisableNotifications'] = $v.'DisableNotifications'
} catch { $results['REG-WindowsFirewall-DomainProfile-DisableNotifications'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'EnableFirewall' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-EnableFirewall'] = $v.'EnableFirewall'
} catch { $results['REG-WindowsFirewall-DomainProfile-EnableFirewall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DefaultInboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-DomainProfile-DefaultInboundAction'] = $v.'DefaultInboundAction'
} catch { $results['REG-WindowsFirewall-DomainProfile-DefaultInboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogDroppedPackets' -ErrorAction Stop
    $results['REG-DomainProfile-Logging-LogDroppedPackets'] = $v.'LogDroppedPackets'
} catch { $results['REG-DomainProfile-Logging-LogDroppedPackets'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogFileSize' -ErrorAction Stop
    $results['REG-DomainProfile-Logging-LogFileSize'] = $v.'LogFileSize'
} catch { $results['REG-DomainProfile-Logging-LogFileSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogSuccessfulConnections' -ErrorAction Stop
    $results['REG-DomainProfile-Logging-LogSuccessfulConnections'] = $v.'LogSuccessfulConnections'
} catch { $results['REG-DomainProfile-Logging-LogSuccessfulConnections'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'EnableFirewall' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-EnableFirewall'] = $v.'EnableFirewall'
} catch { $results['REG-WindowsFirewall-PrivateProfile-EnableFirewall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DisableNotifications' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-DisableNotifications'] = $v.'DisableNotifications'
} catch { $results['REG-WindowsFirewall-PrivateProfile-DisableNotifications'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DefaultInboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-DefaultInboundAction'] = $v.'DefaultInboundAction'
} catch { $results['REG-WindowsFirewall-PrivateProfile-DefaultInboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DefaultOutboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PrivateProfile-DefaultOutboundAction'] = $v.'DefaultOutboundAction'
} catch { $results['REG-WindowsFirewall-PrivateProfile-DefaultOutboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogSuccessfulConnections' -ErrorAction Stop
    $results['REG-PrivateProfile-Logging-LogSuccessfulConnections'] = $v.'LogSuccessfulConnections'
} catch { $results['REG-PrivateProfile-Logging-LogSuccessfulConnections'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogDroppedPackets' -ErrorAction Stop
    $results['REG-PrivateProfile-Logging-LogDroppedPackets'] = $v.'LogDroppedPackets'
} catch { $results['REG-PrivateProfile-Logging-LogDroppedPackets'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogFileSize' -ErrorAction Stop
    $results['REG-PrivateProfile-Logging-LogFileSize'] = $v.'LogFileSize'
} catch { $results['REG-PrivateProfile-Logging-LogFileSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DefaultOutboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-DefaultOutboundAction'] = $v.'DefaultOutboundAction'
} catch { $results['REG-WindowsFirewall-PublicProfile-DefaultOutboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'EnableFirewall' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-EnableFirewall'] = $v.'EnableFirewall'
} catch { $results['REG-WindowsFirewall-PublicProfile-EnableFirewall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DisableNotifications' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-DisableNotifications'] = $v.'DisableNotifications'
} catch { $results['REG-WindowsFirewall-PublicProfile-DisableNotifications'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'AllowLocalIPsecPolicyMerge' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-AllowLocalIPsecPolicyMerge'] = $v.'AllowLocalIPsecPolicyMerge'
} catch { $results['REG-WindowsFirewall-PublicProfile-AllowLocalIPsecPolicyMerge'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'AllowLocalPolicyMerge' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-AllowLocalPolicyMerge'] = $v.'AllowLocalPolicyMerge'
} catch { $results['REG-WindowsFirewall-PublicProfile-AllowLocalPolicyMerge'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DefaultInboundAction' -ErrorAction Stop
    $results['REG-WindowsFirewall-PublicProfile-DefaultInboundAction'] = $v.'DefaultInboundAction'
} catch { $results['REG-WindowsFirewall-PublicProfile-DefaultInboundAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogFileSize' -ErrorAction Stop
    $results['REG-PublicProfile-Logging-LogFileSize'] = $v.'LogFileSize'
} catch { $results['REG-PublicProfile-Logging-LogFileSize'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogDroppedPackets' -ErrorAction Stop
    $results['REG-PublicProfile-Logging-LogDroppedPackets'] = $v.'LogDroppedPackets'
} catch { $results['REG-PublicProfile-Logging-LogDroppedPackets'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogSuccessfulConnections' -ErrorAction Stop
    $results['REG-PublicProfile-Logging-LogSuccessfulConnections'] = $v.'LogSuccessfulConnections'
} catch { $results['REG-PublicProfile-Logging-LogSuccessfulConnections'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters' -Name 'SMB1' -ErrorAction Stop
    $results['REG-LanmanServer-Parameters-SMB1'] = $v.'SMB1'
} catch { $results['REG-LanmanServer-Parameters-SMB1'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\MrxSmb10' -Name 'Start' -ErrorAction Stop
    $results['REG-Services-MrxSmb10-Start'] = $v.'Start'
} catch { $results['REG-Services-MrxSmb10-Start'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters' -Name 'NoNameReleaseOnDemand' -ErrorAction Stop
    $results['REG-Netbt-Parameters-NoNameReleaseOnDemand'] = $v.'NoNameReleaseOnDemand'
} catch { $results['REG-Netbt-Parameters-NoNameReleaseOnDemand'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters' -Name 'NodeType' -ErrorAction Stop
    $results['REG-Netbt-Parameters-NodeType'] = $v.'NodeType'
} catch { $results['REG-Netbt-Parameters-NodeType'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name 'EnableICMPRedirect' -ErrorAction Stop
    $results['REG-Tcpip-Parameters-EnableICMPRedirect'] = $v.'EnableICMPRedirect'
} catch { $results['REG-Tcpip-Parameters-EnableICMPRedirect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name 'DisableIPSourceRouting' -ErrorAction Stop
    $results['REG-Tcpip-Parameters-DisableIPSourceRouting'] = $v.'DisableIPSourceRouting'
} catch { $results['REG-Tcpip-Parameters-DisableIPSourceRouting'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters' -Name 'DisableIPSourceRouting' -ErrorAction Stop
    $results['REG-Tcpip6-Parameters-DisableIPSourceRouting'] = $v.'DisableIPSourceRouting'
} catch { $results['REG-Tcpip6-Parameters-DisableIPSourceRouting'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnablePlainTextPassword' -ErrorAction Stop
    $results['REG-LanmanWorkstation-Parameters-EnablePlainTextPassword'] = $v.'EnablePlainTextPassword'
} catch { $results['REG-LanmanWorkstation-Parameters-EnablePlainTextPassword'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RestrictNullSessAccess' -ErrorAction Stop
    $results['REG-LanManServer-Parameters-RestrictNullSessAccess'] = $v.'RestrictNullSessAccess'
} catch { $results['REG-LanManServer-Parameters-RestrictNullSessAccess'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'requirestrongkey' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-requirestrongkey'] = $v.'requirestrongkey'
} catch { $results['REG-Netlogon-Parameters-requirestrongkey'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'RequireSecuritySignature' -ErrorAction Stop
    $results['REG-LanmanWorkstation-Parameters-RequireSecuritySignature'] = $v.'RequireSecuritySignature'
} catch { $results['REG-LanmanWorkstation-Parameters-RequireSecuritySignature'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'sealsecurechannel' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-sealsecurechannel'] = $v.'sealsecurechannel'
} catch { $results['REG-Netlogon-Parameters-sealsecurechannel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'requiresignorseal' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-requiresignorseal'] = $v.'requiresignorseal'
} catch { $results['REG-Netlogon-Parameters-requiresignorseal'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'signsecurechannel' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-signsecurechannel'] = $v.'signsecurechannel'
} catch { $results['REG-Netlogon-Parameters-signsecurechannel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'requiresecuritysignature' -ErrorAction Stop
    $results['REG-LanManServer-Parameters-requiresecuritysignature'] = $v.'requiresecuritysignature'
} catch { $results['REG-LanManServer-Parameters-requiresecuritysignature'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LDAP' -Name 'LDAPClientIntegrity' -ErrorAction Stop
    $results['REG-Services-LDAP-LDAPClientIntegrity'] = $v.'LDAPClientIntegrity'
} catch { $results['REG-Services-LDAP-LDAPClientIntegrity'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'DisablePasswordChange' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-DisablePasswordChange'] = $v.'DisablePasswordChange'
} catch { $results['REG-Netlogon-Parameters-DisablePasswordChange'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

