# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 9
#
# Types: Registry: 9
# Severity: High: 9

$results = @{}

# --- Registry Checks (9) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'AuditClientDoesNotSupportEncryption' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportEncryption'] = $v.'AuditClientDoesNotSupportEncryption'
} catch { $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportEncryption'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'AuditClientDoesNotSupportSigning' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportSigning'] = $v.'AuditClientDoesNotSupportSigning'
} catch { $results['REG-Windows-LanmanServer-AuditClientDoesNotSupportSigning'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'AuditInsecureGuestLogon' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-AuditInsecureGuestLogon'] = $v.'AuditInsecureGuestLogon'
} catch { $results['REG-Windows-LanmanServer-AuditInsecureGuestLogon'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'EnableAuthRateLimiter' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-EnableAuthRateLimiter'] = $v.'EnableAuthRateLimiter'
} catch { $results['REG-Windows-LanmanServer-EnableAuthRateLimiter'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'MaxSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-MaxSmb2Dialect'] = $v.'MaxSmb2Dialect'
} catch { $results['REG-Windows-LanmanServer-MaxSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'MinSmb2Dialect' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-MinSmb2Dialect'] = $v.'MinSmb2Dialect'
} catch { $results['REG-Windows-LanmanServer-MinSmb2Dialect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\LanmanServer' -Name 'InvalidAuthenticationDelayTimeInMs' -ErrorAction Stop
    $results['REG-Windows-LanmanServer-InvalidAuthenticationDelayTimeInMs'] = $v.'InvalidAuthenticationDelayTimeInMs'
} catch { $results['REG-Windows-LanmanServer-InvalidAuthenticationDelayTimeInMs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RestrictNullSessAccess' -ErrorAction Stop
    $results['REG-LanManServer-Parameters-RestrictNullSessAccess'] = $v.'RestrictNullSessAccess'
} catch { $results['REG-LanManServer-Parameters-RestrictNullSessAccess'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'requiresecuritysignature' -ErrorAction Stop
    $results['REG-LanManServer-Parameters-requiresecuritysignature'] = $v.'requiresecuritysignature'
} catch { $results['REG-LanManServer-Parameters-requiresecuritysignature'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

