# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 16
#
# Types: Registry: 16
# Severity: Critical: 9, High: 5, Medium: 2

$results = @{}

# --- Registry Checks (16) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'RunAsPPL' -ErrorAction Stop
    $results['REG-Control-Lsa-RunAsPPL'] = $v.'RunAsPPL'
} catch { $results['REG-Control-Lsa-RunAsPPL'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse' -ErrorAction Stop
    $results['REG-Control-Lsa-LimitBlankPasswordUse'] = $v.'LimitBlankPasswordUse'
} catch { $results['REG-Control-Lsa-LimitBlankPasswordUse'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymousSAM' -ErrorAction Stop
    $results['REG-Control-Lsa-RestrictAnonymousSAM'] = $v.'RestrictAnonymousSAM'
} catch { $results['REG-Control-Lsa-RestrictAnonymousSAM'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymous' -ErrorAction Stop
    $results['REG-Control-Lsa-RestrictAnonymous'] = $v.'RestrictAnonymous'
} catch { $results['REG-Control-Lsa-RestrictAnonymous'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'SCENoApplyLegacyAuditPolicy' -ErrorAction Stop
    $results['REG-Control-Lsa-SCENoApplyLegacyAuditPolicy'] = $v.'SCENoApplyLegacyAuditPolicy'
} catch { $results['REG-Control-Lsa-SCENoApplyLegacyAuditPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinClientSec' -ErrorAction Stop
    $results['REG-Lsa-MSV1_0-NTLMMinClientSec'] = $v.'NTLMMinClientSec'
} catch { $results['REG-Lsa-MSV1_0-NTLMMinClientSec'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LmCompatibilityLevel' -ErrorAction Stop
    $results['REG-Control-Lsa-LmCompatibilityLevel'] = $v.'LmCompatibilityLevel'
} catch { $results['REG-Control-Lsa-LmCompatibilityLevel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'allownullsessionfallback' -ErrorAction Stop
    $results['REG-Lsa-MSV1_0-allownullsessionfallback'] = $v.'allownullsessionfallback'
} catch { $results['REG-Lsa-MSV1_0-allownullsessionfallback'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinServerSec' -ErrorAction Stop
    $results['REG-Lsa-MSV1_0-NTLMMinServerSec'] = $v.'NTLMMinServerSec'
} catch { $results['REG-Lsa-MSV1_0-NTLMMinServerSec'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'requirestrongkey' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-requirestrongkey'] = $v.'requirestrongkey'
} catch { $results['REG-Netlogon-Parameters-requirestrongkey'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'sealsecurechannel' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-sealsecurechannel'] = $v.'sealsecurechannel'
} catch { $results['REG-Netlogon-Parameters-sealsecurechannel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'requiresignorseal' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-requiresignorseal'] = $v.'requiresignorseal'
} catch { $results['REG-Netlogon-Parameters-requiresignorseal'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'signsecurechannel' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-signsecurechannel'] = $v.'signsecurechannel'
} catch { $results['REG-Netlogon-Parameters-signsecurechannel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\LDAP' -Name 'LDAPClientIntegrity' -ErrorAction Stop
    $results['REG-Services-LDAP-LDAPClientIntegrity'] = $v.'LDAPClientIntegrity'
} catch { $results['REG-Services-LDAP-LDAPClientIntegrity'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictRemoteSAM' -ErrorAction Stop
    $results['REG-Control-Lsa-RestrictRemoteSAM'] = $v.'RestrictRemoteSAM'
} catch { $results['REG-Control-Lsa-RestrictRemoteSAM'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'DisablePasswordChange' -ErrorAction Stop
    $results['REG-Netlogon-Parameters-DisablePasswordChange'] = $v.'DisablePasswordChange'
} catch { $results['REG-Netlogon-Parameters-DisablePasswordChange'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

