# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 10
#
# Types: Registry: 10
# Severity: Medium: 10

$results = @{}

# --- Registry Checks (10) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITHashAlgorithmConfigurationEnabled' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITHashAlgorithmConfigurationEnabled'] = $v.'PKINITHashAlgorithmConfigurationEnabled'
} catch { $results['REG-KDC-Parameters-PKINITHashAlgorithmConfigurationEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA1' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA1'] = $v.'PKINITSHA1'
} catch { $results['REG-KDC-Parameters-PKINITSHA1'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA256' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA256'] = $v.'PKINITSHA256'
} catch { $results['REG-KDC-Parameters-PKINITSHA256'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA384' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA384'] = $v.'PKINITSHA384'
} catch { $results['REG-KDC-Parameters-PKINITSHA384'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\KDC\Parameters' -Name 'PKINITSHA512' -ErrorAction Stop
    $results['REG-KDC-Parameters-PKINITSHA512'] = $v.'PKINITSHA512'
} catch { $results['REG-KDC-Parameters-PKINITSHA512'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitHashAlgorithmConfigurationEnabled' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitHashAlgorithmConfigurationEnabled'] = $v.'PKInitHashAlgorithmConfigurationEnabled'
} catch { $results['REG-Kerberos-Parameters-PKInitHashAlgorithmConfigurationEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA1' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA1'] = $v.'PKInitSHA1'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA1'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA256' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA256'] = $v.'PKInitSHA256'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA256'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA384' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA384'] = $v.'PKInitSHA384'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA384'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'PKInitSHA512' -ErrorAction Stop
    $results['REG-Kerberos-Parameters-PKInitSHA512'] = $v.'PKInitSHA512'
} catch { $results['REG-Kerberos-Parameters-PKInitSHA512'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

