# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 2
#
# Types: Registry: 2
# Severity: Medium: 2

$results = @{}

# --- Registry Checks (2) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\AppPrivacy' -Name 'LetAppsActivateWithVoiceAboveLock' -ErrorAction Stop
    $results['REG-Windows-AppPrivacy-LetAppsActivateWithVoiceAboveLock'] = $v.'LetAppsActivateWithVoiceAboveLock'
} catch { $results['REG-Windows-AppPrivacy-LetAppsActivateWithVoiceAboveLock'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications' -Name 'NoToastApplicationNotificationOnLockScreen' -ErrorAction Stop
    $results['REG-CurrentVersion-PushNotifications-NoToastApplicationNotificationOnLockScreen'] = $v.'NoToastApplicationNotificationOnLockScreen'
} catch { $results['REG-CurrentVersion-PushNotifications-NoToastApplicationNotificationOnLockScreen'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

