# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 40
#
# Types: Registry: 40
# Severity: High: 40

$results = @{}

# --- Registry Checks (40) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Policies\EarlyLaunch' -Name 'DriverLoadPolicy' -ErrorAction Stop
    $results['REG-Policies-EarlyLaunch-DriverLoadPolicy'] = $v.'DriverLoadPolicy'
} catch { $results['REG-Policies-EarlyLaunch-DriverLoadPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender' -Name 'PUAProtection' -ErrorAction Stop
    $results['REG-Microsoft-Windows Defender-PUAProtection'] = $v.'PUAProtection'
} catch { $results['REG-Microsoft-Windows Defender-PUAProtection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender' -Name 'DisableLocalAdminMerge' -ErrorAction Stop
    $results['REG-Microsoft-Windows Defender-DisableLocalAdminMerge'] = $v.'DisableLocalAdminMerge'
} catch { $results['REG-Microsoft-Windows Defender-DisableLocalAdminMerge'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender' -Name 'HideExclusionsFromLocalAdmins' -ErrorAction Stop
    $results['REG-Microsoft-Windows Defender-HideExclusionsFromLocalAdmins'] = $v.'HideExclusionsFromLocalAdmins'
} catch { $results['REG-Microsoft-Windows Defender-HideExclusionsFromLocalAdmins'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender' -Name 'DisableRoutinelyTakingAction' -ErrorAction Stop
    $results['REG-Microsoft-Windows Defender-DisableRoutinelyTakingAction'] = $v.'DisableRoutinelyTakingAction'
} catch { $results['REG-Microsoft-Windows Defender-DisableRoutinelyTakingAction'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Features' -Name 'PassiveRemediation' -ErrorAction Stop
    $results['REG-Windows Defender-Features-PassiveRemediation'] = $v.'PassiveRemediation'
} catch { $results['REG-Windows Defender-Features-PassiveRemediation'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\MpEngine' -Name 'MpCloudBlockLevel' -ErrorAction Stop
    $results['REG-Windows Defender-MpEngine-MpCloudBlockLevel'] = $v.'MpCloudBlockLevel'
} catch { $results['REG-Windows Defender-MpEngine-MpCloudBlockLevel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\MpEngine' -Name 'MpBafsExtendedTimeout' -ErrorAction Stop
    $results['REG-Windows Defender-MpEngine-MpBafsExtendedTimeout'] = $v.'MpBafsExtendedTimeout'
} catch { $results['REG-Windows Defender-MpEngine-MpBafsExtendedTimeout'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\NIS' -Name 'EnableConvertWarnToBlock' -ErrorAction Stop
    $results['REG-Windows Defender-NIS-EnableConvertWarnToBlock'] = $v.'EnableConvertWarnToBlock'
} catch { $results['REG-Windows Defender-NIS-EnableConvertWarnToBlock'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableIOAVProtection' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-DisableIOAVProtection'] = $v.'DisableIOAVProtection'
} catch { $results['REG-Windows Defender-Real-Time Protection-DisableIOAVProtection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableRealtimeMonitoring' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-DisableRealtimeMonitoring'] = $v.'DisableRealtimeMonitoring'
} catch { $results['REG-Windows Defender-Real-Time Protection-DisableRealtimeMonitoring'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableScriptScanning' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-DisableScriptScanning'] = $v.'DisableScriptScanning'
} catch { $results['REG-Windows Defender-Real-Time Protection-DisableScriptScanning'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableBehaviorMonitoring' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-DisableBehaviorMonitoring'] = $v.'DisableBehaviorMonitoring'
} catch { $results['REG-Windows Defender-Real-Time Protection-DisableBehaviorMonitoring'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'RealtimeScanDirection' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-RealtimeScanDirection'] = $v.'RealtimeScanDirection'
} catch { $results['REG-Windows Defender-Real-Time Protection-RealtimeScanDirection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableOnAccessProtection' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-DisableOnAccessProtection'] = $v.'DisableOnAccessProtection'
} catch { $results['REG-Windows Defender-Real-Time Protection-DisableOnAccessProtection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableScanOnRealtimeEnable' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-DisableScanOnRealtimeEnable'] = $v.'DisableScanOnRealtimeEnable'
} catch { $results['REG-Windows Defender-Real-Time Protection-DisableScanOnRealtimeEnable'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'OobeEnableRtpAndSigUpdate' -ErrorAction Stop
    $results['REG-Windows Defender-Real-Time Protection-OobeEnableRtpAndSigUpdate'] = $v.'OobeEnableRtpAndSigUpdate'
} catch { $results['REG-Windows Defender-Real-Time Protection-OobeEnableRtpAndSigUpdate'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Reporting' -Name 'EnableDynamicSignatureDroppedEventReporting' -ErrorAction Stop
    $results['REG-Windows Defender-Reporting-EnableDynamicSignatureDroppedEventReporting'] = $v.'EnableDynamicSignatureDroppedEventReporting'
} catch { $results['REG-Windows Defender-Reporting-EnableDynamicSignatureDroppedEventReporting'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Scan' -Name 'DisableRemovableDriveScanning' -ErrorAction Stop
    $results['REG-Windows Defender-Scan-DisableRemovableDriveScanning'] = $v.'DisableRemovableDriveScanning'
} catch { $results['REG-Windows Defender-Scan-DisableRemovableDriveScanning'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Scan' -Name 'QuickScanIncludeExclusions' -ErrorAction Stop
    $results['REG-Windows Defender-Scan-QuickScanIncludeExclusions'] = $v.'QuickScanIncludeExclusions'
} catch { $results['REG-Windows Defender-Scan-QuickScanIncludeExclusions'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet' -Name 'SpynetReporting' -ErrorAction Stop
    $results['REG-Windows Defender-Spynet-SpynetReporting'] = $v.'SpynetReporting'
} catch { $results['REG-Windows Defender-Spynet-SpynetReporting'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet' -Name 'DisableBlockAtFirstSeen' -ErrorAction Stop
    $results['REG-Windows Defender-Spynet-DisableBlockAtFirstSeen'] = $v.'DisableBlockAtFirstSeen'
} catch { $results['REG-Windows Defender-Spynet-DisableBlockAtFirstSeen'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet' -Name 'SubmitSamplesConsent' -ErrorAction Stop
    $results['REG-Windows Defender-Spynet-SubmitSamplesConsent'] = $v.'SubmitSamplesConsent'
} catch { $results['REG-Windows Defender-Spynet-SubmitSamplesConsent'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR' -Name 'ExploitGuard_ASR_Rules' -ErrorAction Stop
    $results['REG-Windows Defender Exploit Guard-ASR-ExploitGuard_ASR_Rules'] = $v.'ExploitGuard_ASR_Rules'
} catch { $results['REG-Windows Defender Exploit Guard-ASR-ExploitGuard_ASR_Rules'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84' -ErrorAction Stop
    $results['REG-ASR-Rules-75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84'] = $v.'75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84'
} catch { $results['REG-ASR-Rules-75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '3b576869-a4ec-4529-8536-b80a7769e899' -ErrorAction Stop
    $results['REG-ASR-Rules-3b576869-a4ec-4529-8536-b80a7769e899'] = $v.'3b576869-a4ec-4529-8536-b80a7769e899'
} catch { $results['REG-ASR-Rules-3b576869-a4ec-4529-8536-b80a7769e899'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'd4f940ab-401b-4efc-aadc-ad5f3c50688a' -ErrorAction Stop
    $results['REG-ASR-Rules-d4f940ab-401b-4efc-aadc-ad5f3c50688a'] = $v.'d4f940ab-401b-4efc-aadc-ad5f3c50688a'
} catch { $results['REG-ASR-Rules-d4f940ab-401b-4efc-aadc-ad5f3c50688a'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B' -ErrorAction Stop
    $results['REG-ASR-Rules-92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B'] = $v.'92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B'
} catch { $results['REG-ASR-Rules-92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '5beb7efe-fd9a-4556-801d-275e5ffc04cc' -ErrorAction Stop
    $results['REG-ASR-Rules-5beb7efe-fd9a-4556-801d-275e5ffc04cc'] = $v.'5beb7efe-fd9a-4556-801d-275e5ffc04cc'
} catch { $results['REG-ASR-Rules-5beb7efe-fd9a-4556-801d-275e5ffc04cc'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'd3e037e1-3eb8-44c8-a917-57927947596d' -ErrorAction Stop
    $results['REG-ASR-Rules-d3e037e1-3eb8-44c8-a917-57927947596d'] = $v.'d3e037e1-3eb8-44c8-a917-57927947596d'
} catch { $results['REG-ASR-Rules-d3e037e1-3eb8-44c8-a917-57927947596d'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'be9ba2d9-53ea-4cdc-84e5-9b1eeee46550' -ErrorAction Stop
    $results['REG-ASR-Rules-be9ba2d9-53ea-4cdc-84e5-9b1eeee46550'] = $v.'be9ba2d9-53ea-4cdc-84e5-9b1eeee46550'
} catch { $results['REG-ASR-Rules-be9ba2d9-53ea-4cdc-84e5-9b1eeee46550'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2' -ErrorAction Stop
    $results['REG-ASR-Rules-9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2'] = $v.'9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2'
} catch { $results['REG-ASR-Rules-9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4' -ErrorAction Stop
    $results['REG-ASR-Rules-b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4'] = $v.'b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4'
} catch { $results['REG-ASR-Rules-b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '26190899-1602-49e8-8b27-eb1d0a1ce869' -ErrorAction Stop
    $results['REG-ASR-Rules-26190899-1602-49e8-8b27-eb1d0a1ce869'] = $v.'26190899-1602-49e8-8b27-eb1d0a1ce869'
} catch { $results['REG-ASR-Rules-26190899-1602-49e8-8b27-eb1d0a1ce869'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c' -ErrorAction Stop
    $results['REG-ASR-Rules-7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c'] = $v.'7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c'
} catch { $results['REG-ASR-Rules-7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'c1db55ab-c21a-4637-bb3f-a12568109d35' -ErrorAction Stop
    $results['REG-ASR-Rules-c1db55ab-c21a-4637-bb3f-a12568109d35'] = $v.'c1db55ab-c21a-4637-bb3f-a12568109d35'
} catch { $results['REG-ASR-Rules-c1db55ab-c21a-4637-bb3f-a12568109d35'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'e6db77e5-3df2-4cf1-b95a-636979351e5b' -ErrorAction Stop
    $results['REG-ASR-Rules-e6db77e5-3df2-4cf1-b95a-636979351e5b'] = $v.'e6db77e5-3df2-4cf1-b95a-636979351e5b'
} catch { $results['REG-ASR-Rules-e6db77e5-3df2-4cf1-b95a-636979351e5b'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '56a863a9-875e-4185-98a7-b882c64b5ce5' -ErrorAction Stop
    $results['REG-ASR-Rules-56a863a9-875e-4185-98a7-b882c64b5ce5'] = $v.'56a863a9-875e-4185-98a7-b882c64b5ce5'
} catch { $results['REG-ASR-Rules-56a863a9-875e-4185-98a7-b882c64b5ce5'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'd1e49aac-8f56-4280-b9ba-993a6d77406c' -ErrorAction Stop
    $results['REG-ASR-Rules-d1e49aac-8f56-4280-b9ba-993a6d77406c'] = $v.'d1e49aac-8f56-4280-b9ba-993a6d77406c'
} catch { $results['REG-ASR-Rules-d1e49aac-8f56-4280-b9ba-993a6d77406c'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection' -Name 'EnableNetworkProtection' -ErrorAction Stop
    $results['REG-Windows Defender Exploit Guard-Network Protection-EnableNetworkProtection'] = $v.'EnableNetworkProtection'
} catch { $results['REG-Windows Defender Exploit Guard-Network Protection-EnableNetworkProtection'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

