# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 1
#
# Types: Registry: 1
# Severity: Medium: 1

$results = @{}

# --- Registry Checks (1) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\WindowsInkWorkspace' -Name 'AllowWindowsInkWorkspace' -ErrorAction Stop
    $results['REG-Microsoft-WindowsInkWorkspace-AllowWindowsInkWorkspace'] = $v.'AllowWindowsInkWorkspace'
} catch { $results['REG-Microsoft-WindowsInkWorkspace-AllowWindowsInkWorkspace'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

