# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 2
#
# Types: Registry: 2
# Severity: Medium: 2

$results = @{}

# --- Registry Checks (2) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging' -Name 'EnableScriptBlockLogging' -ErrorAction Stop
    $results['REG-PowerShell-ScriptBlockLogging-EnableScriptBlockLogging'] = $v.'EnableScriptBlockLogging'
} catch { $results['REG-PowerShell-ScriptBlockLogging-EnableScriptBlockLogging'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging' -Name '**del.EnableScriptBlockInvocationLogging' -ErrorAction Stop
    $results['REG-PowerShell-ScriptBlockLogging-**del.EnableScriptBlockInvocationLogging'] = $v.'**del.EnableScriptBlockInvocationLogging'
} catch { $results['REG-PowerShell-ScriptBlockLogging-**del.EnableScriptBlockInvocationLogging'] = 'NOT_FOUND' }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

