# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - BitLocker
# Settings: 4
#
# Types: Registry: 4
# Severity: High: 4

$results = @{}

# --- Registry Checks (4) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\FVE' -Name 'UseEnhancedPin' -ErrorAction Stop
    $results['REG-Microsoft-FVE-UseEnhancedPin'] = $v.'UseEnhancedPin'
} catch { $results['REG-Microsoft-FVE-UseEnhancedPin'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\FVE' -Name 'RDVDenyCrossOrg' -ErrorAction Stop
    $results['REG-Microsoft-FVE-RDVDenyCrossOrg'] = $v.'RDVDenyCrossOrg'
} catch { $results['REG-Microsoft-FVE-RDVDenyCrossOrg'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\FVE' -Name 'DisableExternalDMAUnderLock' -ErrorAction Stop
    $results['REG-Microsoft-FVE-DisableExternalDMAUnderLock'] = $v.'DisableExternalDMAUnderLock'
} catch { $results['REG-Microsoft-FVE-DisableExternalDMAUnderLock'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Policies\Microsoft\FVE' -Name 'RDVDenyWriteAccess' -ErrorAction Stop
    $results['REG-Microsoft-FVE-RDVDenyWriteAccess'] = $v.'RDVDenyWriteAccess'
} catch { $results['REG-Microsoft-FVE-RDVDenyWriteAccess'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

