# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 5
#
# Types: Registry: 5
# Severity: Medium: 5

$results = @{}

# --- Registry Checks (5) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters' -Name 'NoNameReleaseOnDemand' -ErrorAction Stop
    $results['REG-Netbt-Parameters-NoNameReleaseOnDemand'] = $v.'NoNameReleaseOnDemand'
} catch { $results['REG-Netbt-Parameters-NoNameReleaseOnDemand'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters' -Name 'NodeType' -ErrorAction Stop
    $results['REG-Netbt-Parameters-NodeType'] = $v.'NodeType'
} catch { $results['REG-Netbt-Parameters-NodeType'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name 'EnableICMPRedirect' -ErrorAction Stop
    $results['REG-Tcpip-Parameters-EnableICMPRedirect'] = $v.'EnableICMPRedirect'
} catch { $results['REG-Tcpip-Parameters-EnableICMPRedirect'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name 'DisableIPSourceRouting' -ErrorAction Stop
    $results['REG-Tcpip-Parameters-DisableIPSourceRouting'] = $v.'DisableIPSourceRouting'
} catch { $results['REG-Tcpip-Parameters-DisableIPSourceRouting'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters' -Name 'DisableIPSourceRouting' -ErrorAction Stop
    $results['REG-Tcpip6-Parameters-DisableIPSourceRouting'] = $v.'DisableIPSourceRouting'
} catch { $results['REG-Tcpip6-Parameters-DisableIPSourceRouting'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

