# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 8
#
# Types: Registry: 8
# Severity: Medium: 8

$results = @{}

# --- Registry Checks (8) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'AllowDomainPINLogon' -ErrorAction Stop
    $results['REG-Windows-System-AllowDomainPINLogon'] = $v.'AllowDomainPINLogon'
} catch { $results['REG-Windows-System-AllowDomainPINLogon'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnumerateLocalUsers' -ErrorAction Stop
    $results['REG-Windows-System-EnumerateLocalUsers'] = $v.'EnumerateLocalUsers'
} catch { $results['REG-Windows-System-EnumerateLocalUsers'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnableSmartScreen' -ErrorAction Stop
    $results['REG-Windows-System-EnableSmartScreen'] = $v.'EnableSmartScreen'
} catch { $results['REG-Windows-System-EnableSmartScreen'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'ShellSmartScreenLevel' -ErrorAction Stop
    $results['REG-Windows-System-ShellSmartScreenLevel'] = $v.'ShellSmartScreenLevel'
} catch { $results['REG-Windows-System-ShellSmartScreenLevel'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'AllowCustomSSPsAPs' -ErrorAction Stop
    $results['REG-Windows-System-AllowCustomSSPsAPs'] = $v.'AllowCustomSSPsAPs'
} catch { $results['REG-Windows-System-AllowCustomSSPsAPs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'RunAsPPL' -ErrorAction Stop
    $results['REG-Windows-System-RunAsPPL'] = $v.'RunAsPPL'
} catch { $results['REG-Windows-System-RunAsPPL'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel' -Name 'DisableExceptionChainValidation' -ErrorAction Stop
    $results['REG-Session Manager-kernel-DisableExceptionChainValidation'] = $v.'DisableExceptionChainValidation'
} catch { $results['REG-Session Manager-kernel-DisableExceptionChainValidation'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Session Manager' -Name 'ProtectionMode' -ErrorAction Stop
    $results['REG-Control-Session Manager-ProtectionMode'] = $v.'ProtectionMode'
} catch { $results['REG-Control-Session Manager-ProtectionMode'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

