# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 2
#
# Types: Registry: 2
# Severity: Medium: 2

$results = @{}

# --- Registry Checks (2) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\WcmSvc\wifinetworkmanager\config' -Name 'AutoConnectAllowedOEM' -ErrorAction Stop
    $results['REG-wifinetworkmanager-config-AutoConnectAllowedOEM'] = $v.'AutoConnectAllowedOEM'
} catch { $results['REG-wifinetworkmanager-config-AutoConnectAllowedOEM'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy' -Name 'fBlockNonDomain' -ErrorAction Stop
    $results['REG-WcmSvc-GroupPolicy-fBlockNonDomain'] = $v.'fBlockNonDomain'
} catch { $results['REG-WcmSvc-GroupPolicy-fBlockNonDomain'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

