# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 2
#
# Types: Registry: 2
# Severity: Low: 2

$results = @{}

# --- Registry Checks (2) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenCamera' -ErrorAction Stop
    $results['REG-Windows-Personalization-NoLockScreenCamera'] = $v.'NoLockScreenCamera'
} catch { $results['REG-Windows-Personalization-NoLockScreenCamera'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenSlideshow' -ErrorAction Stop
    $results['REG-Windows-Personalization-NoLockScreenSlideshow'] = $v.'NoLockScreenSlideshow'
} catch { $results['REG-Windows-Personalization-NoLockScreenSlideshow'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

