# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 3
#
# Types: Registry: 3
# Severity: Low: 3

$results = @{}

# --- Registry Checks (3) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableWindowsConsumerFeatures' -ErrorAction Stop
    $results['REG-Windows-CloudContent-DisableWindowsConsumerFeatures'] = $v.'DisableWindowsConsumerFeatures'
} catch { $results['REG-Windows-CloudContent-DisableWindowsConsumerFeatures'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\GameDVR' -Name 'AllowGameDVR' -ErrorAction Stop
    $results['REG-Windows-GameDVR-AllowGameDVR'] = $v.'AllowGameDVR'
} catch { $results['REG-Windows-GameDVR-AllowGameDVR'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableThirdPartySuggestions' -ErrorAction Stop
    $results['REG-Windows-CloudContent-DisableThirdPartySuggestions'] = $v.'DisableThirdPartySuggestions'
} catch { $results['REG-Windows-CloudContent-DisableThirdPartySuggestions'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

