# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 5
#
# Types: Registry: 5
# Severity: Medium: 5

$results = @{}

# --- Registry Checks (5) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoDriveTypeAutoRun' -ErrorAction Stop
    $results['REG-Policies-Explorer-NoDriveTypeAutoRun'] = $v.'NoDriveTypeAutoRun'
} catch { $results['REG-Policies-Explorer-NoDriveTypeAutoRun'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoWebServices' -ErrorAction Stop
    $results['REG-Policies-Explorer-NoWebServices'] = $v.'NoWebServices'
} catch { $results['REG-Policies-Explorer-NoWebServices'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoAutorun' -ErrorAction Stop
    $results['REG-Policies-Explorer-NoAutorun'] = $v.'NoAutorun'
} catch { $results['REG-Policies-Explorer-NoAutorun'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoAutoplayfornonVolume' -ErrorAction Stop
    $results['REG-Windows-Explorer-NoAutoplayfornonVolume'] = $v.'NoAutoplayfornonVolume'
} catch { $results['REG-Windows-Explorer-NoAutoplayfornonVolume'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'DisableMotWOnInsecurePathCopy' -ErrorAction Stop
    $results['REG-Windows-Explorer-DisableMotWOnInsecurePathCopy'] = $v.'DisableMotWOnInsecurePathCopy'
} catch { $results['REG-Windows-Explorer-DisableMotWOnInsecurePathCopy'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

