# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 4
#
# Types: ServiceConfig: 4
# Severity: Low: 4

$results = @{}

# --- ServiceConfig Checks (4) ---
try {
    $svc = Get-Service -Name 'XboxGipSvc' -ErrorAction Stop
    $results['SVC-XboxGipSvc'] = [int]$svc.StartType
} catch { $results['SVC-XboxGipSvc'] = -1 }
try {
    $svc = Get-Service -Name 'XblAuthManager' -ErrorAction Stop
    $results['SVC-XblAuthManager'] = [int]$svc.StartType
} catch { $results['SVC-XblAuthManager'] = -1 }
try {
    $svc = Get-Service -Name 'XblGameSave' -ErrorAction Stop
    $results['SVC-XblGameSave'] = [int]$svc.StartType
} catch { $results['SVC-XblGameSave'] = -1 }
try {
    $svc = Get-Service -Name 'XboxNetApiSvc' -ErrorAction Stop
    $results['SVC-XboxNetApiSvc'] = [int]$svc.StartType
} catch { $results['SVC-XboxNetApiSvc'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

