# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 10
#
# Types: Registry: 10
# Severity: High: 10

$results = @{}

# --- Registry Checks (10) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name '**del.fUseMailto' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-**del.fUseMailto'] = $v.'**del.fUseMailto'
} catch { $results['REG-Windows NT-Terminal Services-**del.fUseMailto'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fAllowToGetHelp' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-fAllowToGetHelp'] = $v.'fAllowToGetHelp'
} catch { $results['REG-Windows NT-Terminal Services-fAllowToGetHelp'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name '**del.fAllowFullControl' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-**del.fAllowFullControl'] = $v.'**del.fAllowFullControl'
} catch { $results['REG-Windows NT-Terminal Services-**del.fAllowFullControl'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name '**del.MaxTicketExpiry' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-**del.MaxTicketExpiry'] = $v.'**del.MaxTicketExpiry'
} catch { $results['REG-Windows NT-Terminal Services-**del.MaxTicketExpiry'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name '**del.MaxTicketExpiryUnits' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-**del.MaxTicketExpiryUnits'] = $v.'**del.MaxTicketExpiryUnits'
} catch { $results['REG-Windows NT-Terminal Services-**del.MaxTicketExpiryUnits'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'MinEncryptionLevel' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-MinEncryptionLevel'] = $v.'MinEncryptionLevel'
} catch { $results['REG-Windows NT-Terminal Services-MinEncryptionLevel'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fPromptForPassword' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-fPromptForPassword'] = $v.'fPromptForPassword'
} catch { $results['REG-Windows NT-Terminal Services-fPromptForPassword'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fDisableCdm' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-fDisableCdm'] = $v.'fDisableCdm'
} catch { $results['REG-Windows NT-Terminal Services-fDisableCdm'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'DisablePasswordSaving' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-DisablePasswordSaving'] = $v.'DisablePasswordSaving'
} catch { $results['REG-Windows NT-Terminal Services-DisablePasswordSaving'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fEncryptRPCTraffic' -ErrorAction Stop
    $results['REG-Windows NT-Terminal Services-fEncryptRPCTraffic'] = $v.'fEncryptRPCTraffic'
} catch { $results['REG-Windows NT-Terminal Services-fEncryptRPCTraffic'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

