# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Credential Guard
# Settings: 8
#
# Types: Registry: 8
# Severity: Critical: 8

$results = @{}

# --- Registry Checks (8) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'EnableVirtualizationBasedSecurity' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-EnableVirtualizationBasedSecurity'] = $v.'EnableVirtualizationBasedSecurity'
} catch { $results['REG-Windows-DeviceGuard-EnableVirtualizationBasedSecurity'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'RequirePlatformSecurityFeatures' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-RequirePlatformSecurityFeatures'] = $v.'RequirePlatformSecurityFeatures'
} catch { $results['REG-Windows-DeviceGuard-RequirePlatformSecurityFeatures'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'HypervisorEnforcedCodeIntegrity' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-HypervisorEnforcedCodeIntegrity'] = $v.'HypervisorEnforcedCodeIntegrity'
} catch { $results['REG-Windows-DeviceGuard-HypervisorEnforcedCodeIntegrity'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'HVCIMATRequired' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-HVCIMATRequired'] = $v.'HVCIMATRequired'
} catch { $results['REG-Windows-DeviceGuard-HVCIMATRequired'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'LsaCfgFlags' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-LsaCfgFlags'] = $v.'LsaCfgFlags'
} catch { $results['REG-Windows-DeviceGuard-LsaCfgFlags'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'MachineIdentityIsolation' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-MachineIdentityIsolation'] = $v.'MachineIdentityIsolation'
} catch { $results['REG-Windows-DeviceGuard-MachineIdentityIsolation'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'ConfigureSystemGuardLaunch' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-ConfigureSystemGuardLaunch'] = $v.'ConfigureSystemGuardLaunch'
} catch { $results['REG-Windows-DeviceGuard-ConfigureSystemGuardLaunch'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard' -Name 'ConfigureKernelShadowStacksLaunch' -ErrorAction Stop
    $results['REG-Windows-DeviceGuard-ConfigureKernelShadowStacksLaunch'] = $v.'ConfigureKernelShadowStacksLaunch'
} catch { $results['REG-Windows-DeviceGuard-ConfigureKernelShadowStacksLaunch'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

