# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 23
#
# Types: AuditPolicy: 23
# Severity: Critical: 2, High: 11, Medium: 10

$results = @{}

# --- AuditPolicy Checks (23) ---
try {
    $auditRaw = auditpol /get /category:* /r 2>$null
    $auditCsv = $auditRaw | ConvertFrom-Csv
} catch { $auditCsv = @() }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Credential Validation' } | Select-Object -First 1
if ($row) { $results['AUD-AuditCredentialValidation'] = [int]$row.'Setting Value' } else { $results['AUD-AuditCredentialValidation'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Security Group Management' } | Select-Object -First 1
if ($row) { $results['AUD-AuditSecurityGroupManagement'] = [int]$row.'Setting Value' } else { $results['AUD-AuditSecurityGroupManagement'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit User Account Management' } | Select-Object -First 1
if ($row) { $results['AUD-AuditUserAccountManagement'] = [int]$row.'Setting Value' } else { $results['AUD-AuditUserAccountManagement'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit PNP Activity' } | Select-Object -First 1
if ($row) { $results['AUD-AuditPNPActivity'] = [int]$row.'Setting Value' } else { $results['AUD-AuditPNPActivity'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Process Creation' } | Select-Object -First 1
if ($row) { $results['AUD-AuditProcessCreation'] = [int]$row.'Setting Value' } else { $results['AUD-AuditProcessCreation'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Account Lockout' } | Select-Object -First 1
if ($row) { $results['AUD-AuditAccountLockout'] = [int]$row.'Setting Value' } else { $results['AUD-AuditAccountLockout'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Group Membership' } | Select-Object -First 1
if ($row) { $results['AUD-AuditGroupMembership'] = [int]$row.'Setting Value' } else { $results['AUD-AuditGroupMembership'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Logon' } | Select-Object -First 1
if ($row) { $results['AUD-AuditLogon'] = [int]$row.'Setting Value' } else { $results['AUD-AuditLogon'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Other Logon/Logoff Events' } | Select-Object -First 1
if ($row) { $results['AUD-AuditOtherLogonLogoffEvents'] = [int]$row.'Setting Value' } else { $results['AUD-AuditOtherLogonLogoffEvents'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Special Logon' } | Select-Object -First 1
if ($row) { $results['AUD-AuditSpecialLogon'] = [int]$row.'Setting Value' } else { $results['AUD-AuditSpecialLogon'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Detailed File Share' } | Select-Object -First 1
if ($row) { $results['AUD-AuditDetailedFileShare'] = [int]$row.'Setting Value' } else { $results['AUD-AuditDetailedFileShare'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit File Share' } | Select-Object -First 1
if ($row) { $results['AUD-AuditFileShare'] = [int]$row.'Setting Value' } else { $results['AUD-AuditFileShare'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Other Object Access Events' } | Select-Object -First 1
if ($row) { $results['AUD-AuditOtherObjectAccessEvents'] = [int]$row.'Setting Value' } else { $results['AUD-AuditOtherObjectAccessEvents'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Removable Storage' } | Select-Object -First 1
if ($row) { $results['AUD-AuditRemovableStorage'] = [int]$row.'Setting Value' } else { $results['AUD-AuditRemovableStorage'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Audit Policy Change' } | Select-Object -First 1
if ($row) { $results['AUD-AuditAuditPolicyChange'] = [int]$row.'Setting Value' } else { $results['AUD-AuditAuditPolicyChange'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Authentication Policy Change' } | Select-Object -First 1
if ($row) { $results['AUD-AuditAuthenticationPolicyChange'] = [int]$row.'Setting Value' } else { $results['AUD-AuditAuthenticationPolicyChange'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit MPSSVC Rule-Level Policy Change' } | Select-Object -First 1
if ($row) { $results['AUD-AuditMPSSVCRuleLevelPolicyChange'] = [int]$row.'Setting Value' } else { $results['AUD-AuditMPSSVCRuleLevelPolicyChange'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Other Policy Change Events' } | Select-Object -First 1
if ($row) { $results['AUD-AuditOtherPolicyChangeEvents'] = [int]$row.'Setting Value' } else { $results['AUD-AuditOtherPolicyChangeEvents'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Sensitive Privilege Use' } | Select-Object -First 1
if ($row) { $results['AUD-AuditSensitivePrivilegeUse'] = [int]$row.'Setting Value' } else { $results['AUD-AuditSensitivePrivilegeUse'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Other System Events' } | Select-Object -First 1
if ($row) { $results['AUD-AuditOtherSystemEvents'] = [int]$row.'Setting Value' } else { $results['AUD-AuditOtherSystemEvents'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Security State Change' } | Select-Object -First 1
if ($row) { $results['AUD-AuditSecurityStateChange'] = [int]$row.'Setting Value' } else { $results['AUD-AuditSecurityStateChange'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit Security System Extension' } | Select-Object -First 1
if ($row) { $results['AUD-AuditSecuritySystemExtension'] = [int]$row.'Setting Value' } else { $results['AUD-AuditSecuritySystemExtension'] = -1 }
$row = $auditCsv | Where-Object { $_.Subcategory -eq 'Audit System Integrity' } | Select-Object -First 1
if ($row) { $results['AUD-AuditSystemIntegrity'] = [int]$row.'Setting Value' } else { $results['AUD-AuditSystemIntegrity'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

