# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 6
#
# Types: Registry: 6
# Severity: Low: 4, Medium: 2

$results = @{}

# --- Registry Checks (6) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableWindowsConsumerFeatures' -ErrorAction Stop
    $results['REG-Windows-CloudContent-DisableWindowsConsumerFeatures'] = $v.'DisableWindowsConsumerFeatures'
} catch { $results['REG-Windows-CloudContent-DisableWindowsConsumerFeatures'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenCamera' -ErrorAction Stop
    $results['REG-Windows-Personalization-NoLockScreenCamera'] = $v.'NoLockScreenCamera'
} catch { $results['REG-Windows-Personalization-NoLockScreenCamera'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenSlideshow' -ErrorAction Stop
    $results['REG-Windows-Personalization-NoLockScreenSlideshow'] = $v.'NoLockScreenSlideshow'
} catch { $results['REG-Windows-Personalization-NoLockScreenSlideshow'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windows Search' -Name 'AllowIndexingEncryptedStoresOrItems' -ErrorAction Stop
    $results['REG-Windows-Windows Search-AllowIndexingEncryptedStoresOrItems'] = $v.'AllowIndexingEncryptedStoresOrItems'
} catch { $results['REG-Windows-Windows Search-AllowIndexingEncryptedStoresOrItems'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableThirdPartySuggestions' -ErrorAction Stop
    $results['REG-Windows-CloudContent-DisableThirdPartySuggestions'] = $v.'DisableThirdPartySuggestions'
} catch { $results['REG-Windows-CloudContent-DisableThirdPartySuggestions'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications' -Name 'NoToastApplicationNotificationOnLockScreen' -ErrorAction Stop
    $results['REG-CurrentVersion-PushNotifications-NoToastApplicationNotificationOnLockScreen'] = $v.'NoToastApplicationNotificationOnLockScreen'
} catch { $results['REG-CurrentVersion-PushNotifications-NoToastApplicationNotificationOnLockScreen'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

