# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 6
#
# Types: Registry: 6
# Severity: High: 6

$results = @{}

# --- Registry Checks (6) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowDigest' -ErrorAction Stop
    $results['REG-WinRM-Client-AllowDigest'] = $v.'AllowDigest'
} catch { $results['REG-WinRM-Client-AllowDigest'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowUnencryptedTraffic' -ErrorAction Stop
    $results['REG-WinRM-Client-AllowUnencryptedTraffic'] = $v.'AllowUnencryptedTraffic'
} catch { $results['REG-WinRM-Client-AllowUnencryptedTraffic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowBasic' -ErrorAction Stop
    $results['REG-WinRM-Client-AllowBasic'] = $v.'AllowBasic'
} catch { $results['REG-WinRM-Client-AllowBasic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowUnencryptedTraffic' -ErrorAction Stop
    $results['REG-WinRM-Service-AllowUnencryptedTraffic'] = $v.'AllowUnencryptedTraffic'
} catch { $results['REG-WinRM-Service-AllowUnencryptedTraffic'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'DisableRunAs' -ErrorAction Stop
    $results['REG-WinRM-Service-DisableRunAs'] = $v.'DisableRunAs'
} catch { $results['REG-WinRM-Service-DisableRunAs'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowBasic' -ErrorAction Stop
    $results['REG-WinRM-Service-AllowBasic'] = $v.'AllowBasic'
} catch { $results['REG-WinRM-Service-AllowBasic'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

