# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 3
#
# Types: Registry: 3
# Severity: High: 2, Medium: 1

$results = @{}

# --- Registry Checks (3) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\CredUI' -Name 'EnumerateAdministrators' -ErrorAction Stop
    $results['REG-Policies-CredUI-EnumerateAdministrators'] = $v.'EnumerateAdministrators'
} catch { $results['REG-Policies-CredUI-EnumerateAdministrators'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters' -Name 'AllowEncryptionOracle' -ErrorAction Stop
    $results['REG-CredSSP-Parameters-AllowEncryptionOracle'] = $v.'AllowEncryptionOracle'
} catch { $results['REG-CredSSP-Parameters-AllowEncryptionOracle'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CredentialsDelegation' -Name 'AllowProtectedCreds' -ErrorAction Stop
    $results['REG-Windows-CredentialsDelegation-AllowProtectedCreds'] = $v.'AllowProtectedCreds'
} catch { $results['REG-Windows-CredentialsDelegation-AllowProtectedCreds'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

