# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 3
#
# Types: Registry: 3
# Severity: Critical: 1, High: 1, Medium: 1

$results = @{}

# --- Registry Checks (3) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated' -ErrorAction Stop
    $results['REG-Windows-Installer-AlwaysInstallElevated'] = $v.'AlwaysInstallElevated'
} catch { $results['REG-Windows-Installer-AlwaysInstallElevated'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'EnableUserControl' -ErrorAction Stop
    $results['REG-Windows-Installer-EnableUserControl'] = $v.'EnableUserControl'
} catch { $results['REG-Windows-Installer-EnableUserControl'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\AxInstaller' -Name 'OnlyUseAXISForActiveXInstall' -ErrorAction Stop
    $results['REG-Windows-AxInstaller-OnlyUseAXISForActiveXInstall'] = $v.'OnlyUseAXISForActiveXInstall'
} catch { $results['REG-Windows-AxInstaller-OnlyUseAXISForActiveXInstall'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

