# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 136
#
# Types: Registry: 136
# Severity: Low: 40, Medium: 96

$results = @{}

# --- Registry Checks (136) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Feeds' -Name 'DisableEnclosureDownload' -ErrorAction Stop
    $results['REG-Internet Explorer-Feeds-DisableEnclosureDownload'] = $v.'DisableEnclosureDownload'
} catch { $results['REG-Internet Explorer-Feeds-DisableEnclosureDownload'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Ext' -Name 'RunThisTimeEnabled' -ErrorAction Stop
    $results['REG-Policies-Ext-RunThisTimeEnabled'] = $v.'RunThisTimeEnabled'
} catch { $results['REG-Policies-Ext-RunThisTimeEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Ext' -Name 'VersionCheckEnabled' -ErrorAction Stop
    $results['REG-Policies-Ext-VersionCheckEnabled'] = $v.'VersionCheckEnabled'
} catch { $results['REG-Policies-Ext-VersionCheckEnabled'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Download' -Name 'RunInvalidSignatures' -ErrorAction Stop
    $results['REG-Internet Explorer-Download-RunInvalidSignatures'] = $v.'RunInvalidSignatures'
} catch { $results['REG-Internet Explorer-Download-RunInvalidSignatures'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Download' -Name 'CheckExeSignatures' -ErrorAction Stop
    $results['REG-Internet Explorer-Download-CheckExeSignatures'] = $v.'CheckExeSignatures'
} catch { $results['REG-Internet Explorer-Download-CheckExeSignatures'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' -Name 'Isolation64Bit' -ErrorAction Stop
    $results['REG-Internet Explorer-Main-Isolation64Bit'] = $v.'Isolation64Bit'
} catch { $results['REG-Internet Explorer-Main-Isolation64Bit'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' -Name 'DisableEPMCompat' -ErrorAction Stop
    $results['REG-Internet Explorer-Main-DisableEPMCompat'] = $v.'DisableEPMCompat'
} catch { $results['REG-Internet Explorer-Main-DisableEPMCompat'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' -Name 'Isolation' -ErrorAction Stop
    $results['REG-Internet Explorer-Main-Isolation'] = $v.'Isolation'
} catch { $results['REG-Internet Explorer-Main-Isolation'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main' -Name 'DisableInternetExplorerLaunchViaCOM' -ErrorAction Stop
    $results['REG-Internet Explorer-Main-DisableInternetExplorerLaunchViaCOM'] = $v.'DisableInternetExplorerLaunchViaCOM'
} catch { $results['REG-Internet Explorer-Main-DisableInternetExplorerLaunchViaCOM'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_MK_PROTOCOL' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_DISABLE_MK_PROTOCOL-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_DISABLE_MK_PROTOCOL-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_MK_PROTOCOL' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_DISABLE_MK_PROTOCOL-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_DISABLE_MK_PROTOCOL-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_DISABLE_MK_PROTOCOL' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_DISABLE_MK_PROTOCOL-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_DISABLE_MK_PROTOCOL-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_MIME_HANDLING' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_MIME_HANDLING-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_MIME_HANDLING-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_MIME_HANDLING' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_MIME_HANDLING-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_MIME_HANDLING-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_MIME_HANDLING' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_MIME_HANDLING-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_MIME_HANDLING-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_MIME_SNIFFING' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_MIME_SNIFFING-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_MIME_SNIFFING-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_MIME_SNIFFING' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_MIME_SNIFFING-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_MIME_SNIFFING-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_MIME_SNIFFING' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_MIME_SNIFFING-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_MIME_SNIFFING-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_ACTIVEXINSTALL' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_RESTRICT_ACTIVEXINSTALL-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_RESTRICT_ACTIVEXINSTALL-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_ACTIVEXINSTALL' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_RESTRICT_ACTIVEXINSTALL-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_RESTRICT_ACTIVEXINSTALL-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_ACTIVEXINSTALL' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_RESTRICT_ACTIVEXINSTALL-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_RESTRICT_ACTIVEXINSTALL-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_FILEDOWNLOAD' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_RESTRICT_FILEDOWNLOAD-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_RESTRICT_FILEDOWNLOAD-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_FILEDOWNLOAD' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_RESTRICT_FILEDOWNLOAD-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_RESTRICT_FILEDOWNLOAD-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_RESTRICT_FILEDOWNLOAD' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_RESTRICT_FILEDOWNLOAD-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_RESTRICT_FILEDOWNLOAD-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_SECURITYBAND' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_SECURITYBAND-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_SECURITYBAND-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_SECURITYBAND' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_SECURITYBAND-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_SECURITYBAND-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_SECURITYBAND' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_SECURITYBAND-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_SECURITYBAND-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WINDOW_RESTRICTIONS' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_WINDOW_RESTRICTIONS-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_WINDOW_RESTRICTIONS-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WINDOW_RESTRICTIONS' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_WINDOW_RESTRICTIONS-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_WINDOW_RESTRICTIONS-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WINDOW_RESTRICTIONS' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_WINDOW_RESTRICTIONS-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_WINDOW_RESTRICTIONS-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ZONE_ELEVATION' -Name '(Reserved)' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_ZONE_ELEVATION-(Reserved)'] = $v.'(Reserved)'
} catch { $results['REG-FeatureControl-FEATURE_ZONE_ELEVATION-(Reserved)'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ZONE_ELEVATION' -Name 'explorer.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_ZONE_ELEVATION-explorer.exe'] = $v.'explorer.exe'
} catch { $results['REG-FeatureControl-FEATURE_ZONE_ELEVATION-explorer.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ZONE_ELEVATION' -Name 'iexplore.exe' -ErrorAction Stop
    $results['REG-FeatureControl-FEATURE_ZONE_ELEVATION-iexplore.exe'] = $v.'iexplore.exe'
} catch { $results['REG-FeatureControl-FEATURE_ZONE_ELEVATION-iexplore.exe'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\PhishingFilter' -Name 'PreventOverrideAppRepUnknown' -ErrorAction Stop
    $results['REG-Internet Explorer-PhishingFilter-PreventOverrideAppRepUnknown'] = $v.'PreventOverrideAppRepUnknown'
} catch { $results['REG-Internet Explorer-PhishingFilter-PreventOverrideAppRepUnknown'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\PhishingFilter' -Name 'PreventOverride' -ErrorAction Stop
    $results['REG-Internet Explorer-PhishingFilter-PreventOverride'] = $v.'PreventOverride'
} catch { $results['REG-Internet Explorer-PhishingFilter-PreventOverride'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\PhishingFilter' -Name 'EnabledV9' -ErrorAction Stop
    $results['REG-Internet Explorer-PhishingFilter-EnabledV9'] = $v.'EnabledV9'
} catch { $results['REG-Internet Explorer-PhishingFilter-EnabledV9'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Restrictions' -Name 'NoCrashDetection' -ErrorAction Stop
    $results['REG-Internet Explorer-Restrictions-NoCrashDetection'] = $v.'NoCrashDetection'
} catch { $results['REG-Internet Explorer-Restrictions-NoCrashDetection'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Security' -Name 'DisableSecuritySettingsCheck' -ErrorAction Stop
    $results['REG-Internet Explorer-Security-DisableSecuritySettingsCheck'] = $v.'DisableSecuritySettingsCheck'
} catch { $results['REG-Internet Explorer-Security-DisableSecuritySettingsCheck'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Security\ActiveX' -Name 'BlockNonAdminActiveXInstall' -ErrorAction Stop
    $results['REG-Security-ActiveX-BlockNonAdminActiveXInstall'] = $v.'BlockNonAdminActiveXInstall'
} catch { $results['REG-Security-ActiveX-BlockNonAdminActiveXInstall'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'Security_zones_map_edit' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-Security_zones_map_edit'] = $v.'Security_zones_map_edit'
} catch { $results['REG-CurrentVersion-Internet Settings-Security_zones_map_edit'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'Security_options_edit' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-Security_options_edit'] = $v.'Security_options_edit'
} catch { $results['REG-CurrentVersion-Internet Settings-Security_options_edit'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'Security_HKLM_only' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-Security_HKLM_only'] = $v.'Security_HKLM_only'
} catch { $results['REG-CurrentVersion-Internet Settings-Security_HKLM_only'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'CertificateRevocation' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-CertificateRevocation'] = $v.'CertificateRevocation'
} catch { $results['REG-CurrentVersion-Internet Settings-CertificateRevocation'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'PreventIgnoreCertErrors' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-PreventIgnoreCertErrors'] = $v.'PreventIgnoreCertErrors'
} catch { $results['REG-CurrentVersion-Internet Settings-PreventIgnoreCertErrors'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'WarnOnBadCertRecving' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-WarnOnBadCertRecving'] = $v.'WarnOnBadCertRecving'
} catch { $results['REG-CurrentVersion-Internet Settings-WarnOnBadCertRecving'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'EnableSSL3Fallback' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-EnableSSL3Fallback'] = $v.'EnableSSL3Fallback'
} catch { $results['REG-CurrentVersion-Internet Settings-EnableSSL3Fallback'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings' -Name 'SecureProtocols' -ErrorAction Stop
    $results['REG-CurrentVersion-Internet Settings-SecureProtocols'] = $v.'SecureProtocols'
} catch { $results['REG-CurrentVersion-Internet Settings-SecureProtocols'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\0' -Name '1C00' -ErrorAction Stop
    $results['REG-Lockdown_Zones-0-1C00'] = $v.'1C00'
} catch { $results['REG-Lockdown_Zones-0-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\1' -Name '1C00' -ErrorAction Stop
    $results['REG-Lockdown_Zones-1-1C00'] = $v.'1C00'
} catch { $results['REG-Lockdown_Zones-1-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\2' -Name '1C00' -ErrorAction Stop
    $results['REG-Lockdown_Zones-2-1C00'] = $v.'1C00'
} catch { $results['REG-Lockdown_Zones-2-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\3' -Name '2301' -ErrorAction Stop
    $results['REG-Lockdown_Zones-3-2301'] = $v.'2301'
} catch { $results['REG-Lockdown_Zones-3-2301'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\4' -Name '2301' -ErrorAction Stop
    $results['REG-Lockdown_Zones-4-2301'] = $v.'2301'
} catch { $results['REG-Lockdown_Zones-4-2301'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\4' -Name '1C00' -ErrorAction Stop
    $results['REG-Lockdown_Zones-4-1C00'] = $v.'1C00'
} catch { $results['REG-Lockdown_Zones-4-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap' -Name 'UNCAsIntranet' -ErrorAction Stop
    $results['REG-Internet Settings-ZoneMap-UNCAsIntranet'] = $v.'UNCAsIntranet'
} catch { $results['REG-Internet Settings-ZoneMap-UNCAsIntranet'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0' -Name '1C00' -ErrorAction Stop
    $results['REG-Zones-0-1C00'] = $v.'1C00'
} catch { $results['REG-Zones-0-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0' -Name '270C' -ErrorAction Stop
    $results['REG-Zones-0-270C'] = $v.'270C'
} catch { $results['REG-Zones-0-270C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1' -Name '270C' -ErrorAction Stop
    $results['REG-Zones-1-270C'] = $v.'270C'
} catch { $results['REG-Zones-1-270C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1' -Name '1201' -ErrorAction Stop
    $results['REG-Zones-1-1201'] = $v.'1201'
} catch { $results['REG-Zones-1-1201'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1' -Name '1C00' -ErrorAction Stop
    $results['REG-Zones-1-1C00'] = $v.'1C00'
} catch { $results['REG-Zones-1-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2' -Name '1C00' -ErrorAction Stop
    $results['REG-Zones-2-1C00'] = $v.'1C00'
} catch { $results['REG-Zones-2-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2' -Name '270C' -ErrorAction Stop
    $results['REG-Zones-2-270C'] = $v.'270C'
} catch { $results['REG-Zones-2-270C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2' -Name '1201' -ErrorAction Stop
    $results['REG-Zones-2-1201'] = $v.'1201'
} catch { $results['REG-Zones-2-1201'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2001' -ErrorAction Stop
    $results['REG-Zones-3-2001'] = $v.'2001'
} catch { $results['REG-Zones-3-2001'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2102' -ErrorAction Stop
    $results['REG-Zones-3-2102'] = $v.'2102'
} catch { $results['REG-Zones-3-2102'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1802' -ErrorAction Stop
    $results['REG-Zones-3-1802'] = $v.'1802'
} catch { $results['REG-Zones-3-1802'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '160A' -ErrorAction Stop
    $results['REG-Zones-3-160A'] = $v.'160A'
} catch { $results['REG-Zones-3-160A'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1201' -ErrorAction Stop
    $results['REG-Zones-3-1201'] = $v.'1201'
} catch { $results['REG-Zones-3-1201'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1406' -ErrorAction Stop
    $results['REG-Zones-3-1406'] = $v.'1406'
} catch { $results['REG-Zones-3-1406'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1804' -ErrorAction Stop
    $results['REG-Zones-3-1804'] = $v.'1804'
} catch { $results['REG-Zones-3-1804'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2200' -ErrorAction Stop
    $results['REG-Zones-3-2200'] = $v.'2200'
} catch { $results['REG-Zones-3-2200'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1209' -ErrorAction Stop
    $results['REG-Zones-3-1209'] = $v.'1209'
} catch { $results['REG-Zones-3-1209'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1206' -ErrorAction Stop
    $results['REG-Zones-3-1206'] = $v.'1206'
} catch { $results['REG-Zones-3-1206'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1809' -ErrorAction Stop
    $results['REG-Zones-3-1809'] = $v.'1809'
} catch { $results['REG-Zones-3-1809'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2500' -ErrorAction Stop
    $results['REG-Zones-3-2500'] = $v.'2500'
} catch { $results['REG-Zones-3-2500'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2103' -ErrorAction Stop
    $results['REG-Zones-3-2103'] = $v.'2103'
} catch { $results['REG-Zones-3-2103'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1606' -ErrorAction Stop
    $results['REG-Zones-3-1606'] = $v.'1606'
} catch { $results['REG-Zones-3-1606'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2402' -ErrorAction Stop
    $results['REG-Zones-3-2402'] = $v.'2402'
} catch { $results['REG-Zones-3-2402'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2004' -ErrorAction Stop
    $results['REG-Zones-3-2004'] = $v.'2004'
} catch { $results['REG-Zones-3-2004'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1C00' -ErrorAction Stop
    $results['REG-Zones-3-1C00'] = $v.'1C00'
} catch { $results['REG-Zones-3-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1001' -ErrorAction Stop
    $results['REG-Zones-3-1001'] = $v.'1001'
} catch { $results['REG-Zones-3-1001'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1A00' -ErrorAction Stop
    $results['REG-Zones-3-1A00'] = $v.'1A00'
} catch { $results['REG-Zones-3-1A00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2708' -ErrorAction Stop
    $results['REG-Zones-3-2708'] = $v.'2708'
} catch { $results['REG-Zones-3-2708'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1004' -ErrorAction Stop
    $results['REG-Zones-3-1004'] = $v.'1004'
} catch { $results['REG-Zones-3-1004'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '120b' -ErrorAction Stop
    $results['REG-Zones-3-120b'] = $v.'120b'
} catch { $results['REG-Zones-3-120b'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1407' -ErrorAction Stop
    $results['REG-Zones-3-1407'] = $v.'1407'
} catch { $results['REG-Zones-3-1407'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1409' -ErrorAction Stop
    $results['REG-Zones-3-1409'] = $v.'1409'
} catch { $results['REG-Zones-3-1409'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '270C' -ErrorAction Stop
    $results['REG-Zones-3-270C'] = $v.'270C'
} catch { $results['REG-Zones-3-270C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1607' -ErrorAction Stop
    $results['REG-Zones-3-1607'] = $v.'1607'
} catch { $results['REG-Zones-3-1607'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2709' -ErrorAction Stop
    $results['REG-Zones-3-2709'] = $v.'2709'
} catch { $results['REG-Zones-3-2709'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2101' -ErrorAction Stop
    $results['REG-Zones-3-2101'] = $v.'2101'
} catch { $results['REG-Zones-3-2101'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '2301' -ErrorAction Stop
    $results['REG-Zones-3-2301'] = $v.'2301'
} catch { $results['REG-Zones-3-2301'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '1806' -ErrorAction Stop
    $results['REG-Zones-3-1806'] = $v.'1806'
} catch { $results['REG-Zones-3-1806'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '120c' -ErrorAction Stop
    $results['REG-Zones-3-120c'] = $v.'120c'
} catch { $results['REG-Zones-3-120c'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3' -Name '140C' -ErrorAction Stop
    $results['REG-Zones-3-140C'] = $v.'140C'
} catch { $results['REG-Zones-3-140C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1608' -ErrorAction Stop
    $results['REG-Zones-4-1608'] = $v.'1608'
} catch { $results['REG-Zones-4-1608'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1201' -ErrorAction Stop
    $results['REG-Zones-4-1201'] = $v.'1201'
} catch { $results['REG-Zones-4-1201'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1001' -ErrorAction Stop
    $results['REG-Zones-4-1001'] = $v.'1001'
} catch { $results['REG-Zones-4-1001'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1607' -ErrorAction Stop
    $results['REG-Zones-4-1607'] = $v.'1607'
} catch { $results['REG-Zones-4-1607'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '120b' -ErrorAction Stop
    $results['REG-Zones-4-120b'] = $v.'120b'
} catch { $results['REG-Zones-4-120b'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1809' -ErrorAction Stop
    $results['REG-Zones-4-1809'] = $v.'1809'
} catch { $results['REG-Zones-4-1809'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1004' -ErrorAction Stop
    $results['REG-Zones-4-1004'] = $v.'1004'
} catch { $results['REG-Zones-4-1004'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1606' -ErrorAction Stop
    $results['REG-Zones-4-1606'] = $v.'1606'
} catch { $results['REG-Zones-4-1606'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1407' -ErrorAction Stop
    $results['REG-Zones-4-1407'] = $v.'1407'
} catch { $results['REG-Zones-4-1407'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '160A' -ErrorAction Stop
    $results['REG-Zones-4-160A'] = $v.'160A'
} catch { $results['REG-Zones-4-160A'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1406' -ErrorAction Stop
    $results['REG-Zones-4-1406'] = $v.'1406'
} catch { $results['REG-Zones-4-1406'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2102' -ErrorAction Stop
    $results['REG-Zones-4-2102'] = $v.'2102'
} catch { $results['REG-Zones-4-2102'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2004' -ErrorAction Stop
    $results['REG-Zones-4-2004'] = $v.'2004'
} catch { $results['REG-Zones-4-2004'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2200' -ErrorAction Stop
    $results['REG-Zones-4-2200'] = $v.'2200'
} catch { $results['REG-Zones-4-2200'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2000' -ErrorAction Stop
    $results['REG-Zones-4-2000'] = $v.'2000'
} catch { $results['REG-Zones-4-2000'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1402' -ErrorAction Stop
    $results['REG-Zones-4-1402'] = $v.'1402'
} catch { $results['REG-Zones-4-1402'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1803' -ErrorAction Stop
    $results['REG-Zones-4-1803'] = $v.'1803'
} catch { $results['REG-Zones-4-1803'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2402' -ErrorAction Stop
    $results['REG-Zones-4-2402'] = $v.'2402'
} catch { $results['REG-Zones-4-2402'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1400' -ErrorAction Stop
    $results['REG-Zones-4-1400'] = $v.'1400'
} catch { $results['REG-Zones-4-1400'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1A00' -ErrorAction Stop
    $results['REG-Zones-4-1A00'] = $v.'1A00'
} catch { $results['REG-Zones-4-1A00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2001' -ErrorAction Stop
    $results['REG-Zones-4-2001'] = $v.'2001'
} catch { $results['REG-Zones-4-2001'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2500' -ErrorAction Stop
    $results['REG-Zones-4-2500'] = $v.'2500'
} catch { $results['REG-Zones-4-2500'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1409' -ErrorAction Stop
    $results['REG-Zones-4-1409'] = $v.'1409'
} catch { $results['REG-Zones-4-1409'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1C00' -ErrorAction Stop
    $results['REG-Zones-4-1C00'] = $v.'1C00'
} catch { $results['REG-Zones-4-1C00'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1209' -ErrorAction Stop
    $results['REG-Zones-4-1209'] = $v.'1209'
} catch { $results['REG-Zones-4-1209'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '270C' -ErrorAction Stop
    $results['REG-Zones-4-270C'] = $v.'270C'
} catch { $results['REG-Zones-4-270C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1206' -ErrorAction Stop
    $results['REG-Zones-4-1206'] = $v.'1206'
} catch { $results['REG-Zones-4-1206'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2708' -ErrorAction Stop
    $results['REG-Zones-4-2708'] = $v.'2708'
} catch { $results['REG-Zones-4-2708'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1802' -ErrorAction Stop
    $results['REG-Zones-4-1802'] = $v.'1802'
} catch { $results['REG-Zones-4-1802'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2103' -ErrorAction Stop
    $results['REG-Zones-4-2103'] = $v.'2103'
} catch { $results['REG-Zones-4-2103'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2709' -ErrorAction Stop
    $results['REG-Zones-4-2709'] = $v.'2709'
} catch { $results['REG-Zones-4-2709'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1405' -ErrorAction Stop
    $results['REG-Zones-4-1405'] = $v.'1405'
} catch { $results['REG-Zones-4-1405'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2101' -ErrorAction Stop
    $results['REG-Zones-4-2101'] = $v.'2101'
} catch { $results['REG-Zones-4-2101'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '2301' -ErrorAction Stop
    $results['REG-Zones-4-2301'] = $v.'2301'
} catch { $results['REG-Zones-4-2301'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1200' -ErrorAction Stop
    $results['REG-Zones-4-1200'] = $v.'1200'
} catch { $results['REG-Zones-4-1200'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1804' -ErrorAction Stop
    $results['REG-Zones-4-1804'] = $v.'1804'
} catch { $results['REG-Zones-4-1804'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '1806' -ErrorAction Stop
    $results['REG-Zones-4-1806'] = $v.'1806'
} catch { $results['REG-Zones-4-1806'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '120c' -ErrorAction Stop
    $results['REG-Zones-4-120c'] = $v.'120c'
} catch { $results['REG-Zones-4-120c'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4' -Name '140C' -ErrorAction Stop
    $results['REG-Zones-4-140C'] = $v.'140C'
} catch { $results['REG-Zones-4-140C'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Internet Explorer\Control Panel' -Name 'FormSuggest Passwords' -ErrorAction Stop
    $results['REG-Internet Explorer-Control Panel-FormSuggest Passwords'] = $v.'FormSuggest Passwords'
} catch { $results['REG-Internet Explorer-Control Panel-FormSuggest Passwords'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Internet Explorer\Main' -Name 'FormSuggest PW Ask' -ErrorAction Stop
    $results['REG-Internet Explorer-Main-FormSuggest PW Ask'] = $v.'FormSuggest PW Ask'
} catch { $results['REG-Internet Explorer-Main-FormSuggest PW Ask'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKU:\Software\Policies\Microsoft\Internet Explorer\Main' -Name 'FormSuggest Passwords' -ErrorAction Stop
    $results['REG-Internet Explorer-Main-FormSuggest Passwords'] = $v.'FormSuggest Passwords'
} catch { $results['REG-Internet Explorer-Main-FormSuggest Passwords'] = 'NOT_FOUND' }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

