# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 10
#
# Types: Registry: 10
# Severity: High: 1, Medium: 9

$results = @{}

# --- Registry Checks (10) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'DisableWebPnPDownload' -ErrorAction Stop
    $results['REG-Windows NT-Printers-DisableWebPnPDownload'] = $v.'DisableWebPnPDownload'
} catch { $results['REG-Windows NT-Printers-DisableWebPnPDownload'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'RedirectionGuardPolicy' -ErrorAction Stop
    $results['REG-Windows NT-Printers-RedirectionGuardPolicy'] = $v.'RedirectionGuardPolicy'
} catch { $results['REG-Windows NT-Printers-RedirectionGuardPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'CopyFilesPolicy' -ErrorAction Stop
    $results['REG-Windows NT-Printers-CopyFilesPolicy'] = $v.'CopyFilesPolicy'
} catch { $results['REG-Windows NT-Printers-CopyFilesPolicy'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'RestrictDriverInstallationToAdministrators' -ErrorAction Stop
    $results['REG-Printers-PointAndPrint-RestrictDriverInstallationToAdministrators'] = $v.'RestrictDriverInstallationToAdministrators'
} catch { $results['REG-Printers-PointAndPrint-RestrictDriverInstallationToAdministrators'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC' -Name 'RpcUseNamedPipeProtocol' -ErrorAction Stop
    $results['REG-Printers-RPC-RpcUseNamedPipeProtocol'] = $v.'RpcUseNamedPipeProtocol'
} catch { $results['REG-Printers-RPC-RpcUseNamedPipeProtocol'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC' -Name 'RpcAuthentication' -ErrorAction Stop
    $results['REG-Printers-RPC-RpcAuthentication'] = $v.'RpcAuthentication'
} catch { $results['REG-Printers-RPC-RpcAuthentication'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC' -Name 'RpcProtocols' -ErrorAction Stop
    $results['REG-Printers-RPC-RpcProtocols'] = $v.'RpcProtocols'
} catch { $results['REG-Printers-RPC-RpcProtocols'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC' -Name 'ForceKerberosForRpc' -ErrorAction Stop
    $results['REG-Printers-RPC-ForceKerberosForRpc'] = $v.'ForceKerberosForRpc'
} catch { $results['REG-Printers-RPC-ForceKerberosForRpc'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC' -Name 'RpcTcpPort' -ErrorAction Stop
    $results['REG-Printers-RPC-RpcTcpPort'] = $v.'RpcTcpPort'
} catch { $results['REG-Printers-RPC-RpcTcpPort'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Print' -Name 'RpcAuthnLevelPrivacyEnabled' -ErrorAction Stop
    $results['REG-Control-Print-RpcAuthnLevelPrivacyEnabled'] = $v.'RpcAuthnLevelPrivacyEnabled'
} catch { $results['REG-Control-Print-RpcAuthnLevelPrivacyEnabled'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

