# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 4
#
# Types: Registry: 4
# Severity: High: 2, Medium: 2

$results = @{}

# --- Registry Checks (4) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel' -Name 'DisableExceptionChainValidation' -ErrorAction Stop
    $results['REG-Session Manager-kernel-DisableExceptionChainValidation'] = $v.'DisableExceptionChainValidation'
} catch { $results['REG-Session Manager-kernel-DisableExceptionChainValidation'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters' -Name 'SMB1' -ErrorAction Stop
    $results['REG-LanmanServer-Parameters-SMB1'] = $v.'SMB1'
} catch { $results['REG-LanmanServer-Parameters-SMB1'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\MrxSmb10' -Name 'Start' -ErrorAction Stop
    $results['REG-Services-MrxSmb10-Start'] = $v.'Start'
} catch { $results['REG-Services-MrxSmb10-Start'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Session Manager' -Name 'ProtectionMode' -ErrorAction Stop
    $results['REG-Control-Session Manager-ProtectionMode'] = $v.'ProtectionMode'
} catch { $results['REG-Control-Session Manager-ProtectionMode'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

