# Auto-generated by GPOBaselineForge on 2026-03-27
# Baseline: MSFT Windows 11 25H2 - Computer
# Settings: 7
#
# Types: Registry: 7
# Severity: Medium: 7

$results = @{}

# --- Registry Checks (7) ---
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_ShowSharedAccessUI' -ErrorAction Stop
    $results['REG-Windows-Network Connections-NC_ShowSharedAccessUI'] = $v.'NC_ShowSharedAccessUI'
} catch { $results['REG-Windows-Network Connections-NC_ShowSharedAccessUI'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider' -Name 'EnableMailslots' -ErrorAction Stop
    $results['REG-Windows-NetworkProvider-EnableMailslots'] = $v.'EnableMailslots'
} catch { $results['REG-Windows-NetworkProvider-EnableMailslots'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\SYSVOL' -ErrorAction Stop
    $results['REG--*-SYSVOL'] = $v.'\\*\SYSVOL'
} catch { $results['REG--*-SYSVOL'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\NETLOGON' -ErrorAction Stop
    $results['REG--*-NETLOGON'] = $v.'\\*\NETLOGON'
} catch { $results['REG--*-NETLOGON'] = 'NOT_FOUND' }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableMulticast' -ErrorAction Stop
    $results['REG-Windows NT-DNSClient-EnableMulticast'] = $v.'EnableMulticast'
} catch { $results['REG-Windows NT-DNSClient-EnableMulticast'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableNetbios' -ErrorAction Stop
    $results['REG-Windows NT-DNSClient-EnableNetbios'] = $v.'EnableNetbios'
} catch { $results['REG-Windows NT-DNSClient-EnableNetbios'] = -1 }
try {
    $v = Get-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Rpc' -Name 'RestrictRemoteClients' -ErrorAction Stop
    $results['REG-Windows NT-Rpc-RestrictRemoteClients'] = $v.'RestrictRemoteClients'
} catch { $results['REG-Windows NT-Rpc-RestrictRemoteClients'] = -1 }

# Output results as JSON (Intune custom compliance requirement)
$results | ConvertTo-Json -Compress

